// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: chunk/chunk.proto

package chunk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PutChunkRequest is sent as a stream. The first message MUST contain
// chunk_id, checksum and (for encrypted volumes) volume_id; subsequent
// messages carry data fragments.
type PutChunkRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ChunkId  string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data     []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Checksum uint32                 `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// volume_id identifies the logical volume this chunk belongs to. The
	// server uses it to look up a per-volume Dataset Key (DK) for
	// transparent AES-GCM encryption. If empty, or if the volume has no DK
	// cached, the chunk is stored as-is (unencrypted).
	VolumeId      string `protobuf:"bytes,4,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkRequest) Reset() {
	*x = PutChunkRequest{}
	mi := &file_chunk_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkRequest) ProtoMessage() {}

func (x *PutChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkRequest.ProtoReflect.Descriptor instead.
func (*PutChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *PutChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *PutChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutChunkRequest) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *PutChunkRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type PutChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	BytesWritten  int64                  `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkResponse) Reset() {
	*x = PutChunkResponse{}
	mi := &file_chunk_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkResponse) ProtoMessage() {}

func (x *PutChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkResponse.ProtoReflect.Descriptor instead.
func (*PutChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *PutChunkResponse) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *PutChunkResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type GetChunkRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChunkId string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	// volume_id is required to decrypt chunks stored on encrypted volumes.
	// When empty, the chunk is returned as-stored (unencrypted path).
	VolumeId      string `protobuf:"bytes,2,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_chunk_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *GetChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *GetChunkRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

// GetChunkResponse is streamed back to the caller. The first message
// includes chunk_id, checksum and the first data fragment. Subsequent
// messages carry the remaining data fragments.
type GetChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      uint32                 `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_chunk_chunk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_chunk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_chunk_proto_rawDescGZIP(), []int{3}
}

func (x *GetChunkResponse) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetChunkResponse) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_chunk_chunk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_chunk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_chunk_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_chunk_chunk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_chunk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_chunk_proto_rawDescGZIP(), []int{5}
}

type HasChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasChunkRequest) Reset() {
	*x = HasChunkRequest{}
	mi := &file_chunk_chunk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasChunkRequest) ProtoMessage() {}

func (x *HasChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_chunk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasChunkRequest.ProtoReflect.Descriptor instead.
func (*HasChunkRequest) Descriptor() ([]byte, []int) {
	return file_chunk_chunk_proto_rawDescGZIP(), []int{6}
}

func (x *HasChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type HasChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasChunkResponse) Reset() {
	*x = HasChunkResponse{}
	mi := &file_chunk_chunk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasChunkResponse) ProtoMessage() {}

func (x *HasChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chunk_chunk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasChunkResponse.ProtoReflect.Descriptor instead.
func (*HasChunkResponse) Descriptor() ([]byte, []int) {
	return file_chunk_chunk_proto_rawDescGZIP(), []int{7}
}

func (x *HasChunkResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_chunk_chunk_proto protoreflect.FileDescriptor

const file_chunk_chunk_proto_rawDesc = "" +
	"\n" +
	"\x11chunk/chunk.proto\x12\x05chunk\"y\n" +
	"\x0fPutChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\rR\bchecksum\x12\x1b\n" +
	"\tvolume_id\x18\x04 \x01(\tR\bvolumeId\"R\n" +
	"\x10PutChunkResponse\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x03R\fbytesWritten\"I\n" +
	"\x0fGetChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1b\n" +
	"\tvolume_id\x18\x02 \x01(\tR\bvolumeId\"]\n" +
	"\x10GetChunkResponse\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\rR\bchecksum\"/\n" +
	"\x12DeleteChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"\x15\n" +
	"\x13DeleteChunkResponse\",\n" +
	"\x0fHasChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"*\n" +
	"\x10HasChunkResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\x8f\x02\n" +
	"\fChunkService\x12=\n" +
	"\bPutChunk\x12\x16.chunk.PutChunkRequest\x1a\x17.chunk.PutChunkResponse(\x01\x12=\n" +
	"\bGetChunk\x12\x16.chunk.GetChunkRequest\x1a\x17.chunk.GetChunkResponse0\x01\x12D\n" +
	"\vDeleteChunk\x12\x19.chunk.DeleteChunkRequest\x1a\x1a.chunk.DeleteChunkResponse\x12;\n" +
	"\bHasChunk\x12\x16.chunk.HasChunkRequest\x1a\x17.chunk.HasChunkResponseB5Z3github.com/azrtydxb/novanas/storage/api/proto/chunkb\x06proto3"

var (
	file_chunk_chunk_proto_rawDescOnce sync.Once
	file_chunk_chunk_proto_rawDescData []byte
)

func file_chunk_chunk_proto_rawDescGZIP() []byte {
	file_chunk_chunk_proto_rawDescOnce.Do(func() {
		file_chunk_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chunk_chunk_proto_rawDesc), len(file_chunk_chunk_proto_rawDesc)))
	})
	return file_chunk_chunk_proto_rawDescData
}

var file_chunk_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chunk_chunk_proto_goTypes = []any{
	(*PutChunkRequest)(nil),     // 0: chunk.PutChunkRequest
	(*PutChunkResponse)(nil),    // 1: chunk.PutChunkResponse
	(*GetChunkRequest)(nil),     // 2: chunk.GetChunkRequest
	(*GetChunkResponse)(nil),    // 3: chunk.GetChunkResponse
	(*DeleteChunkRequest)(nil),  // 4: chunk.DeleteChunkRequest
	(*DeleteChunkResponse)(nil), // 5: chunk.DeleteChunkResponse
	(*HasChunkRequest)(nil),     // 6: chunk.HasChunkRequest
	(*HasChunkResponse)(nil),    // 7: chunk.HasChunkResponse
}
var file_chunk_chunk_proto_depIdxs = []int32{
	0, // 0: chunk.ChunkService.PutChunk:input_type -> chunk.PutChunkRequest
	2, // 1: chunk.ChunkService.GetChunk:input_type -> chunk.GetChunkRequest
	4, // 2: chunk.ChunkService.DeleteChunk:input_type -> chunk.DeleteChunkRequest
	6, // 3: chunk.ChunkService.HasChunk:input_type -> chunk.HasChunkRequest
	1, // 4: chunk.ChunkService.PutChunk:output_type -> chunk.PutChunkResponse
	3, // 5: chunk.ChunkService.GetChunk:output_type -> chunk.GetChunkResponse
	5, // 6: chunk.ChunkService.DeleteChunk:output_type -> chunk.DeleteChunkResponse
	7, // 7: chunk.ChunkService.HasChunk:output_type -> chunk.HasChunkResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chunk_chunk_proto_init() }
func file_chunk_chunk_proto_init() {
	if File_chunk_chunk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chunk_chunk_proto_rawDesc), len(file_chunk_chunk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chunk_chunk_proto_goTypes,
		DependencyIndexes: file_chunk_chunk_proto_depIdxs,
		MessageInfos:      file_chunk_chunk_proto_msgTypes,
	}.Build()
	File_chunk_chunk_proto = out.File
	file_chunk_chunk_proto_goTypes = nil
	file_chunk_chunk_proto_depIdxs = nil
}
