package reconciler

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"
)

// OpenBaoPolicy is the minimal shape controllers pass to OpenBaoClient.
//
// Name is the policy name (typically tenant-scoped, e.g. "tenant-alice").
// HCL is the rendered policy document.
type OpenBaoPolicy struct {
	Name string
	HCL  string
}

// OpenBaoAuthRole maps a Kubernetes service account to a set of policies
// via the kubernetes auth method.
type OpenBaoAuthRole struct {
	Name                  string
	BoundServiceAccount   string
	BoundNamespace        string
	Policies              []string
	TTLSeconds            int
	MaxTTLSeconds         int
}

// OpenBaoClient abstracts the subset of OpenBao admin API operations the
// NovaNas controllers need for per-tenant policy management.
//
// Real implementations wrap the OpenBao REST client; tests inject
// NoopOpenBaoClient or a test double.
type OpenBaoClient interface {
	EnsurePolicy(ctx context.Context, p OpenBaoPolicy) error
	DeletePolicy(ctx context.Context, name string) error

	EnsureAuthRole(ctx context.Context, r OpenBaoAuthRole) error
	DeleteAuthRole(ctx context.Context, name string) error
}

// NoopOpenBaoClient is the default fallback used when no OpenBao wiring is
// configured. All methods return success without doing anything, which
// lets controllers exercise their happy path in dev/test environments.
type NoopOpenBaoClient struct{}

// EnsurePolicy is a no-op.
func (NoopOpenBaoClient) EnsurePolicy(_ context.Context, _ OpenBaoPolicy) error { return nil }

// DeletePolicy is a no-op.
func (NoopOpenBaoClient) DeletePolicy(_ context.Context, _ string) error { return nil }

// EnsureAuthRole is a no-op.
func (NoopOpenBaoClient) EnsureAuthRole(_ context.Context, _ OpenBaoAuthRole) error { return nil }

// DeleteAuthRole is a no-op.
func (NoopOpenBaoClient) DeleteAuthRole(_ context.Context, _ string) error { return nil }

// FakeOpenBaoClient is a recording test double. Tests can inspect the
// Policies and Roles maps to assert on the sequence of calls.
type FakeOpenBaoClient struct {
	Policies map[string]string
	Roles    map[string]OpenBaoAuthRole
	Err      error
}

// NewFakeOpenBaoClient returns an initialized fake client for tests.
func NewFakeOpenBaoClient() *FakeOpenBaoClient {
	return &FakeOpenBaoClient{
		Policies: map[string]string{},
		Roles:    map[string]OpenBaoAuthRole{},
	}
}

// EnsurePolicy records the policy HCL.
func (f *FakeOpenBaoClient) EnsurePolicy(_ context.Context, p OpenBaoPolicy) error {
	if f.Err != nil {
		return f.Err
	}
	f.Policies[p.Name] = p.HCL
	return nil
}

// DeletePolicy removes a recorded policy.
func (f *FakeOpenBaoClient) DeletePolicy(_ context.Context, name string) error {
	if f.Err != nil {
		return f.Err
	}
	delete(f.Policies, name)
	return nil
}

// EnsureAuthRole records an auth role.
func (f *FakeOpenBaoClient) EnsureAuthRole(_ context.Context, r OpenBaoAuthRole) error {
	if f.Err != nil {
		return f.Err
	}
	f.Roles[r.Name] = r
	return nil
}

// DeleteAuthRole removes a recorded auth role.
func (f *FakeOpenBaoClient) DeleteAuthRole(_ context.Context, name string) error {
	if f.Err != nil {
		return f.Err
	}
	delete(f.Roles, name)
	return nil
}

// DefaultTenantPolicyTemplate is the default HCL template used to generate
// a per-tenant policy. It grants the tenant read/write access to its own
// key-value tree and the ability to read shared tenant metadata. The
// template receives {{.User}} as the tenant/user name.
const DefaultTenantPolicyTemplate = `# Auto-generated by NovaNas operator. Do not edit.
# Tenant: {{.User}}

path "tenants/data/{{.User}}/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "tenants/metadata/{{.User}}/*" {
  capabilities = ["read", "list", "delete"]
}

path "shared/data/tenants/{{.User}}" {
  capabilities = ["read"]
}
`

// RenderTenantPolicy renders a policy HCL document from the given template
// and user name. If tmpl is empty DefaultTenantPolicyTemplate is used.
func RenderTenantPolicy(tmpl, user string) (string, error) {
	if strings.TrimSpace(user) == "" {
		return "", fmt.Errorf("openbao: user name is required")
	}
	if tmpl == "" {
		tmpl = DefaultTenantPolicyTemplate
	}
	t, err := template.New("tenant-policy").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("openbao: parse policy template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, struct{ User string }{User: user}); err != nil {
		return "", fmt.Errorf("openbao: render policy: %w", err)
	}
	return buf.String(), nil
}

// TenantPolicyName returns the canonical policy name for a tenant/user.
func TenantPolicyName(user string) string {
	return "tenant-" + user
}

// TenantAuthRoleName returns the canonical kubernetes-auth role name for
// a tenant/user.
func TenantAuthRoleName(user string) string {
	return "tenant-" + user
}
