{{- if .Values.postgresql.enabled -}}
{{- $ns := include "novanas.systemNamespace" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: novanas-postgresql
  namespace: {{ $ns }}
  labels:
    {{- include "novanas.componentLabels" (dict "ctx" . "component" "postgresql") | nindent 4 }}
spec:
  serviceName: novanas-postgresql-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "novanas.selectorLabels" (dict "ctx" . "component" "postgresql") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "novanas.componentLabels" (dict "ctx" . "component" "postgresql") | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.image.registry }}/{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: tcp
              containerPort: 5432
          env:
            # Always run as the `postgres` superuser. Application roles
            # (novanas, keycloak, openbao) are created by the
            # post-install databases-job which connects as postgres.
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: novanas-postgresql
                  key: postgres-password
            - name: POSTGRES_DB
              value: "postgres"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml (.Values.postgresql.resources | default dict) | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- with .Values.postgresql.persistence.storageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size | default "5Gi" }}
{{- end }}
