// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AuditEventOutcome.
const (
	AuditEventOutcomeAccepted AuditEventOutcome = "accepted"
	AuditEventOutcomeRejected AuditEventOutcome = "rejected"
)

// Valid indicates whether the value is a known member of the AuditEventOutcome enum.
func (e AuditEventOutcome) Valid() bool {
	switch e {
	case AuditEventOutcomeAccepted:
		return true
	case AuditEventOutcomeRejected:
		return true
	default:
		return false
	}
}

// Defines values for DatasetType.
const (
	DatasetTypeFilesystem DatasetType = "filesystem"
	DatasetTypeVolume     DatasetType = "volume"
)

// Valid indicates whether the value is a known member of the DatasetType enum.
func (e DatasetType) Valid() bool {
	switch e {
	case DatasetTypeFilesystem:
		return true
	case DatasetTypeVolume:
		return true
	default:
		return false
	}
}

// Defines values for DatasetACEType.
const (
	Allow DatasetACEType = "allow"
	Deny  DatasetACEType = "deny"
)

// Valid indicates whether the value is a known member of the DatasetACEType enum.
func (e DatasetACEType) Valid() bool {
	switch e {
	case Allow:
		return true
	case Deny:
		return true
	default:
		return false
	}
}

// Defines values for DatasetACLPerm.
const (
	Append      DatasetACLPerm = "append"
	Delete      DatasetACLPerm = "delete"
	DeleteChild DatasetACLPerm = "delete_child"
	Execute     DatasetACLPerm = "execute"
	FullControl DatasetACLPerm = "full_control"
	Modify      DatasetACLPerm = "modify"
	Read        DatasetACLPerm = "read"
	ReadAcl     DatasetACLPerm = "read_acl"
	ReadAttrs   DatasetACLPerm = "read_attrs"
	ReadOnly    DatasetACLPerm = "read_only"
	ReadXattr   DatasetACLPerm = "read_xattr"
	Synchronize DatasetACLPerm = "synchronize"
	Write       DatasetACLPerm = "write"
	WriteAcl    DatasetACLPerm = "write_acl"
	WriteAttrs  DatasetACLPerm = "write_attrs"
	WriteOwner  DatasetACLPerm = "write_owner"
	WriteXattr  DatasetACLPerm = "write_xattr"
)

// Valid indicates whether the value is a known member of the DatasetACLPerm enum.
func (e DatasetACLPerm) Valid() bool {
	switch e {
	case Append:
		return true
	case Delete:
		return true
	case DeleteChild:
		return true
	case Execute:
		return true
	case FullControl:
		return true
	case Modify:
		return true
	case Read:
		return true
	case ReadAcl:
		return true
	case ReadAttrs:
		return true
	case ReadOnly:
		return true
	case ReadXattr:
		return true
	case Synchronize:
		return true
	case Write:
		return true
	case WriteAcl:
		return true
	case WriteAttrs:
		return true
	case WriteOwner:
		return true
	case WriteXattr:
		return true
	default:
		return false
	}
}

// Defines values for DatasetCreateSpecType.
const (
	DatasetCreateSpecTypeFilesystem DatasetCreateSpecType = "filesystem"
	DatasetCreateSpecTypeVolume     DatasetCreateSpecType = "volume"
)

// Valid indicates whether the value is a known member of the DatasetCreateSpecType enum.
func (e DatasetCreateSpecType) Valid() bool {
	switch e {
	case DatasetCreateSpecTypeFilesystem:
		return true
	case DatasetCreateSpecTypeVolume:
		return true
	default:
		return false
	}
}

// Defines values for DatasetDiffEntryChange.
const (
	M     DatasetDiffEntryChange = "M"
	Minus DatasetDiffEntryChange = "-"
	Plus  DatasetDiffEntryChange = "+"
	R     DatasetDiffEntryChange = "R"
)

// Valid indicates whether the value is a known member of the DatasetDiffEntryChange enum.
func (e DatasetDiffEntryChange) Valid() bool {
	switch e {
	case M:
		return true
	case Minus:
		return true
	case Plus:
		return true
	case R:
		return true
	default:
		return false
	}
}

// Defines values for DatasetInheritFlag.
const (
	Dir         DatasetInheritFlag = "dir"
	File        DatasetInheritFlag = "file"
	InheritOnly DatasetInheritFlag = "inherit_only"
	NoPropagate DatasetInheritFlag = "no_propagate"
)

// Valid indicates whether the value is a known member of the DatasetInheritFlag enum.
func (e DatasetInheritFlag) Valid() bool {
	switch e {
	case Dir:
		return true
	case File:
		return true
	case InheritOnly:
		return true
	case NoPropagate:
		return true
	default:
		return false
	}
}

// Defines values for IscsiPortalTransport.
const (
	IscsiPortalTransportIser IscsiPortalTransport = "iser"
	IscsiPortalTransportTcp  IscsiPortalTransport = "tcp"
)

// Valid indicates whether the value is a known member of the IscsiPortalTransport enum.
func (e IscsiPortalTransport) Valid() bool {
	switch e {
	case IscsiPortalTransportIser:
		return true
	case IscsiPortalTransportTcp:
		return true
	default:
		return false
	}
}

// Defines values for NetworkBondMode.
const (
	ActiveBackup NetworkBondMode = "active-backup"
	BalanceAlb   NetworkBondMode = "balance-alb"
	BalanceRr    NetworkBondMode = "balance-rr"
	BalanceTlb   NetworkBondMode = "balance-tlb"
	BalanceXor   NetworkBondMode = "balance-xor"
	Broadcast    NetworkBondMode = "broadcast"
	N8023ad      NetworkBondMode = "802.3ad"
)

// Valid indicates whether the value is a known member of the NetworkBondMode enum.
func (e NetworkBondMode) Valid() bool {
	switch e {
	case ActiveBackup:
		return true
	case BalanceAlb:
		return true
	case BalanceRr:
		return true
	case BalanceTlb:
		return true
	case BalanceXor:
		return true
	case Broadcast:
		return true
	case N8023ad:
		return true
	default:
		return false
	}
}

// Defines values for NetworkInterfaceKind.
const (
	Bond      NetworkInterfaceKind = "bond"
	Interface NetworkInterfaceKind = "interface"
	Vlan      NetworkInterfaceKind = "vlan"
)

// Valid indicates whether the value is a known member of the NetworkInterfaceKind enum.
func (e NetworkInterfaceKind) Valid() bool {
	switch e {
	case Bond:
		return true
	case Interface:
		return true
	case Vlan:
		return true
	default:
		return false
	}
}

// Defines values for NetworkInterfaceConfigDhcp.
const (
	Empty NetworkInterfaceConfigDhcp = ""
	Ipv4  NetworkInterfaceConfigDhcp = "ipv4"
	Ipv6  NetworkInterfaceConfigDhcp = "ipv6"
	No    NetworkInterfaceConfigDhcp = "no"
	Yes   NetworkInterfaceConfigDhcp = "yes"
)

// Valid indicates whether the value is a known member of the NetworkInterfaceConfigDhcp enum.
func (e NetworkInterfaceConfigDhcp) Valid() bool {
	switch e {
	case Empty:
		return true
	case Ipv4:
		return true
	case Ipv6:
		return true
	case No:
		return true
	case Yes:
		return true
	default:
		return false
	}
}

// Defines values for NvmeofDHChapConfigDhgroup.
const (
	Ffdhe2048   NvmeofDHChapConfigDhgroup = "ffdhe2048"
	Ffdhe3072   NvmeofDHChapConfigDhgroup = "ffdhe3072"
	Ffdhe4096   NvmeofDHChapConfigDhgroup = "ffdhe4096"
	Ffdhe6144   NvmeofDHChapConfigDhgroup = "ffdhe6144"
	Ffdhe8192   NvmeofDHChapConfigDhgroup = "ffdhe8192"
	LessThannil NvmeofDHChapConfigDhgroup = "<nil>"
)

// Valid indicates whether the value is a known member of the NvmeofDHChapConfigDhgroup enum.
func (e NvmeofDHChapConfigDhgroup) Valid() bool {
	switch e {
	case Ffdhe2048:
		return true
	case Ffdhe3072:
		return true
	case Ffdhe4096:
		return true
	case Ffdhe6144:
		return true
	case Ffdhe8192:
		return true
	case LessThannil:
		return true
	default:
		return false
	}
}

// Defines values for NvmeofDHChapConfigHash.
const (
	HmacSha256 NvmeofDHChapConfigHash = "hmac(sha256)"
	HmacSha384 NvmeofDHChapConfigHash = "hmac(sha384)"
	HmacSha512 NvmeofDHChapConfigHash = "hmac(sha512)"
)

// Valid indicates whether the value is a known member of the NvmeofDHChapConfigHash enum.
func (e NvmeofDHChapConfigHash) Valid() bool {
	switch e {
	case HmacSha256:
		return true
	case HmacSha384:
		return true
	case HmacSha512:
		return true
	default:
		return false
	}
}

// Defines values for NvmeofPortTransport.
const (
	NvmeofPortTransportRdma NvmeofPortTransport = "rdma"
	NvmeofPortTransportTcp  NvmeofPortTransport = "tcp"
)

// Valid indicates whether the value is a known member of the NvmeofPortTransport enum.
func (e NvmeofPortTransport) Valid() bool {
	switch e {
	case NvmeofPortTransportRdma:
		return true
	case NvmeofPortTransportTcp:
		return true
	default:
		return false
	}
}

// Defines values for Protocol.
const (
	Nfs Protocol = "nfs"
	Smb Protocol = "smb"
)

// Valid indicates whether the value is a known member of the Protocol enum.
func (e Protocol) Valid() bool {
	switch e {
	case Nfs:
		return true
	case Smb:
		return true
	default:
		return false
	}
}

// Defines values for SMTPConfigTlsMode.
const (
	None     SMTPConfigTlsMode = "none"
	Starttls SMTPConfigTlsMode = "starttls"
	Tls      SMTPConfigTlsMode = "tls"
)

// Valid indicates whether the value is a known member of the SMTPConfigTlsMode enum.
func (e SMTPConfigTlsMode) Valid() bool {
	switch e {
	case None:
		return true
	case Starttls:
		return true
	case Tls:
		return true
	default:
		return false
	}
}

// Defines values for SambaGlobalsOptsAclProfile.
const (
	Nfsv4 SambaGlobalsOptsAclProfile = "nfsv4"
	Posix SambaGlobalsOptsAclProfile = "posix"
)

// Valid indicates whether the value is a known member of the SambaGlobalsOptsAclProfile enum.
func (e SambaGlobalsOptsAclProfile) Valid() bool {
	switch e {
	case Nfsv4:
		return true
	case Posix:
		return true
	default:
		return false
	}
}

// Defines values for SambaGlobalsOptsSecurityMode.
const (
	Ads  SambaGlobalsOptsSecurityMode = "ads"
	User SambaGlobalsOptsSecurityMode = "user"
)

// Valid indicates whether the value is a known member of the SambaGlobalsOptsSecurityMode enum.
func (e SambaGlobalsOptsSecurityMode) Valid() bool {
	switch e {
	case Ads:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for ScrubPolicyPriority.
const (
	High   ScrubPolicyPriority = "high"
	Low    ScrubPolicyPriority = "low"
	Medium ScrubPolicyPriority = "medium"
)

// Valid indicates whether the value is a known member of the ScrubPolicyPriority enum.
func (e ScrubPolicyPriority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for VdevSpecType.
const (
	VdevSpecTypeDisk   VdevSpecType = "disk"
	VdevSpecTypeMirror VdevSpecType = "mirror"
	VdevSpecTypeRaidz1 VdevSpecType = "raidz1"
	VdevSpecTypeRaidz2 VdevSpecType = "raidz2"
	VdevSpecTypeRaidz3 VdevSpecType = "raidz3"
	VdevSpecTypeStripe VdevSpecType = "stripe"
)

// Valid indicates whether the value is a known member of the VdevSpecType enum.
func (e VdevSpecType) Valid() bool {
	switch e {
	case VdevSpecTypeDisk:
		return true
	case VdevSpecTypeMirror:
		return true
	case VdevSpecTypeRaidz1:
		return true
	case VdevSpecTypeRaidz2:
		return true
	case VdevSpecTypeRaidz3:
		return true
	case VdevSpecTypeStripe:
		return true
	default:
		return false
	}
}

// Defines values for ListAuditParamsOutcome.
const (
	ListAuditParamsOutcomeAccepted ListAuditParamsOutcome = "accepted"
	ListAuditParamsOutcomeRejected ListAuditParamsOutcome = "rejected"
)

// Valid indicates whether the value is a known member of the ListAuditParamsOutcome enum.
func (e ListAuditParamsOutcome) Valid() bool {
	switch e {
	case ListAuditParamsOutcomeAccepted:
		return true
	case ListAuditParamsOutcomeRejected:
		return true
	default:
		return false
	}
}

// Defines values for ExportAuditParamsFormat.
const (
	Csv   ExportAuditParamsFormat = "csv"
	Jsonl ExportAuditParamsFormat = "jsonl"
)

// Valid indicates whether the value is a known member of the ExportAuditParamsFormat enum.
func (e ExportAuditParamsFormat) Valid() bool {
	switch e {
	case Csv:
		return true
	case Jsonl:
		return true
	default:
		return false
	}
}

// Defines values for ExportAuditParamsOutcome.
const (
	ExportAuditParamsOutcomeAccepted ExportAuditParamsOutcome = "accepted"
	ExportAuditParamsOutcomeRejected ExportAuditParamsOutcome = "rejected"
)

// Valid indicates whether the value is a known member of the ExportAuditParamsOutcome enum.
func (e ExportAuditParamsOutcome) Valid() bool {
	switch e {
	case ExportAuditParamsOutcomeAccepted:
		return true
	case ExportAuditParamsOutcomeRejected:
		return true
	default:
		return false
	}
}

// Defines values for ListJobsParamsState.
const (
	Cancelled   ListJobsParamsState = "cancelled"
	Failed      ListJobsParamsState = "failed"
	Interrupted ListJobsParamsState = "interrupted"
	Queued      ListJobsParamsState = "queued"
	Running     ListJobsParamsState = "running"
	Succeeded   ListJobsParamsState = "succeeded"
)

// Valid indicates whether the value is a known member of the ListJobsParamsState enum.
func (e ListJobsParamsState) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Failed:
		return true
	case Interrupted:
		return true
	case Queued:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	// Action HTTP method + path, e.g. 'POST /api/v1/pools'
	Action  string            `json:"action"`
	Actor   *string           `json:"actor,omitempty"`
	Id      int64             `json:"id"`
	Outcome AuditEventOutcome `json:"outcome"`

	// Payload Redacted request body (when JSON).
	Payload   interface{} `json:"payload,omitempty"`
	RequestId *string     `json:"request_id,omitempty"`

	// Resource Resource path (URL of the affected object)
	Resource  string    `json:"resource"`
	Timestamp time.Time `json:"timestamp"`
}

// AuditEventOutcome defines model for AuditEvent.Outcome.
type AuditEventOutcome string

// AuditListResponse defines model for AuditListResponse.
type AuditListResponse struct {
	Items []AuditEvent `json:"items"`

	// NextCursor Opaque cursor; pass back as ?cursor=... to fetch the next
	// page. Empty when there are no more rows.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// AuditSummaryRow defines model for AuditSummaryRow.
type AuditSummaryRow struct {
	Action  string `json:"action"`
	Actor   string `json:"actor"`
	Count   int64  `json:"count"`
	Outcome string `json:"outcome"`
}

// Bookmark defines model for Bookmark.
type Bookmark struct {
	CreationUnix int64  `json:"creationUnix"`
	Name         string `json:"name"`
}

// BookmarkDestroyRequest defines model for BookmarkDestroyRequest.
type BookmarkDestroyRequest struct {
	// Bookmark Either a short name (combined with the URL dataset) or full `<dataset>#<short>`.
	Bookmark string `json:"bookmark"`
}

// ChangeKeyRequest defines model for ChangeKeyRequest.
type ChangeKeyRequest struct {
	Properties map[string]string `json:"properties"`
}

// Dataset defines model for Dataset.
type Dataset struct {
	AvailableBytes  *int         `json:"availableBytes,omitempty"`
	Compression     *string      `json:"compression,omitempty"`
	Mountpoint      *string      `json:"mountpoint,omitempty"`
	Name            *string      `json:"name,omitempty"`
	RecordSizeBytes *int         `json:"recordSizeBytes,omitempty"`
	ReferencedBytes *int         `json:"referencedBytes,omitempty"`
	Type            *DatasetType `json:"type,omitempty"`
	UsedBytes       *int         `json:"usedBytes,omitempty"`
}

// DatasetType defines model for Dataset.Type.
type DatasetType string

// DatasetACE defines model for DatasetACE.
type DatasetACE struct {
	Inheritance *[]DatasetInheritFlag `json:"inheritance,omitempty"`
	Permissions []DatasetACLPerm      `json:"permissions"`

	// Principal user:<name>", "group:<name>", or one of "OWNER@","GROUP@","EVERYONE@"
	Principal string         `json:"principal"`
	Type      DatasetACEType `json:"type"`
}

// DatasetACEType defines model for DatasetACE.Type.
type DatasetACEType string

// DatasetACLAppendRequest defines model for DatasetACLAppendRequest.
type DatasetACLAppendRequest struct {
	Ace DatasetACE `json:"ace"`
}

// DatasetACLPerm defines model for DatasetACLPerm.
type DatasetACLPerm string

// DatasetACLSetRequest defines model for DatasetACLSetRequest.
type DatasetACLSetRequest struct {
	Aces []DatasetACE `json:"aces"`
}

// DatasetBookmarkRequest defines model for DatasetBookmarkRequest.
type DatasetBookmarkRequest struct {
	// Bookmark Full bookmark name `<dataset>#<short>`.
	Bookmark string `json:"bookmark"`
}

// DatasetCloneRequest defines model for DatasetCloneRequest.
type DatasetCloneRequest struct {
	Properties *map[string]string `json:"properties,omitempty"`
	Target     string             `json:"target"`
}

// DatasetCreateSpec defines model for DatasetCreateSpec.
type DatasetCreateSpec struct {
	Name            string                `json:"name"`
	Parent          string                `json:"parent"`
	Properties      *map[string]string    `json:"properties,omitempty"`
	Type            DatasetCreateSpecType `json:"type"`
	VolumeSizeBytes *int                  `json:"volumeSizeBytes,omitempty"`
}

// DatasetCreateSpecType defines model for DatasetCreateSpec.Type.
type DatasetCreateSpecType string

// DatasetDetail defines model for DatasetDetail.
type DatasetDetail struct {
	Dataset    *Dataset           `json:"dataset,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// DatasetDiffEntry defines model for DatasetDiffEntry.
type DatasetDiffEntry struct {
	// Change Change type — added
	Change DatasetDiffEntryChange `json:"change"`

	// NewPath Set only when change is `R` (rename)
	NewPath *string `json:"newPath,omitempty"`
	Path    string  `json:"path"`
}

// DatasetDiffEntryChange Change type — added
type DatasetDiffEntryChange string

// DatasetInheritFlag defines model for DatasetInheritFlag.
type DatasetInheritFlag string

// DatasetRenameRequest defines model for DatasetRenameRequest.
type DatasetRenameRequest struct {
	NewName   string `json:"newName"`
	Recursive *bool  `json:"recursive,omitempty"`
}

// Disk defines model for Disk.
type Disk struct {
	InUseByPool *bool   `json:"inUseByPool,omitempty"`
	Model       *string `json:"model,omitempty"`
	Name        *string `json:"name,omitempty"`
	Rotational  *bool   `json:"rotational,omitempty"`
	Serial      *string `json:"serial,omitempty"`
	SizeBytes   *int64  `json:"sizeBytes,omitempty"`
	Wwn         *string `json:"wwn,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Hold defines model for Hold.
type Hold struct {
	CreationUnix int64  `json:"creationUnix"`
	Snapshot     string `json:"snapshot"`
	Tag          string `json:"tag"`
}

// Identity Authenticated principal as projected from a verified JWT.
type Identity struct {
	Email             *openapi_types.Email `json:"email,omitempty"`
	ExpiresAt         time.Time            `json:"expiresAt"`
	PreferredUsername *string              `json:"preferredUsername,omitempty"`

	// Realm Keycloak realm derived from the issuer.
	Realm  *string  `json:"realm,omitempty"`
	Roles  []string `json:"roles"`
	Scopes []string `json:"scopes"`

	// Sub Subject (stable user id).
	Sub string `json:"sub"`
}

// IscsiACL defines model for IscsiACL.
type IscsiACL struct {
	// ChapSecret 12-16 characters per RFC 3720; never returned on reads
	ChapSecret   *string `json:"chapSecret,omitempty"`
	ChapUser     *string `json:"chapUser,omitempty"`
	InitiatorIqn string  `json:"initiatorIqn"`
}

// IscsiLUN defines model for IscsiLUN.
type IscsiLUN struct {
	Backstore string `json:"backstore"`
	Id        int    `json:"id"`

	// Zvol /dev/zvol/<pool>/<name>
	Zvol *string `json:"zvol,omitempty"`
}

// IscsiPortal defines model for IscsiPortal.
type IscsiPortal struct {
	Ip        string                `json:"ip"`
	Port      int                   `json:"port"`
	Transport *IscsiPortalTransport `json:"transport,omitempty"`
}

// IscsiPortalTransport defines model for IscsiPortal.Transport.
type IscsiPortalTransport string

// IscsiTarget defines model for IscsiTarget.
type IscsiTarget struct {
	Iqn string `json:"iqn"`
}

// IscsiTargetDetail defines model for IscsiTargetDetail.
type IscsiTargetDetail struct {
	Acls    *[]IscsiACL    `json:"acls,omitempty"`
	Luns    *[]IscsiLUN    `json:"luns,omitempty"`
	Portals *[]IscsiPortal `json:"portals,omitempty"`
	Target  *IscsiTarget   `json:"target,omitempty"`
}

// Job defines model for Job.
type Job struct {
	Command    *string             `json:"command,omitempty"`
	CreatedAt  *time.Time          `json:"createdAt,omitempty"`
	Error      *string             `json:"error,omitempty"`
	ExitCode   *int                `json:"exitCode,omitempty"`
	FinishedAt *time.Time          `json:"finishedAt,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Kind       *string             `json:"kind,omitempty"`
	StartedAt  *time.Time          `json:"startedAt,omitempty"`
	State      *string             `json:"state,omitempty"`
	Stderr     *string             `json:"stderr,omitempty"`
	Stdout     *string             `json:"stdout,omitempty"`
	Target     *string             `json:"target,omitempty"`
}

// Krb5Config defines model for Krb5Config.
type Krb5Config struct {
	// DefaultRealm Uppercase realm name (e.g. EXAMPLE.COM)
	DefaultRealm   string               `json:"defaultRealm"`
	DnsLookupKdc   *bool                `json:"dnsLookupKdc,omitempty"`
	DnsLookupRealm *bool                `json:"dnsLookupRealm,omitempty"`
	DomainRealm    *map[string]string   `json:"domainRealm,omitempty"`
	Realms         map[string]Krb5Realm `json:"realms"`
}

// Krb5IdmapdConfig defines model for Krb5IdmapdConfig.
type Krb5IdmapdConfig struct {
	// Domain NFSv4 ID-map domain (typically lowercase realm)
	Domain    string `json:"domain"`
	Verbosity *int   `json:"verbosity,omitempty"`
}

// Krb5KDCStatus defines model for Krb5KDCStatus.
type Krb5KDCStatus struct {
	// DatabaseExists Has the principal DB been bootstrapped?
	DatabaseExists bool `json:"databaseExists"`

	// PrincipalCount Number of principals known to the KDC
	PrincipalCount int `json:"principalCount"`

	// Realm Configured realm (e.g. NOVANAS.LOCAL)
	Realm string `json:"realm"`

	// Running Is krb5kdc.service active?
	Running bool `json:"running"`

	// StashSealed Is the master-key stash file present?
	StashSealed bool `json:"stashSealed"`
}

// Krb5KeytabEntry defines model for Krb5KeytabEntry.
type Krb5KeytabEntry struct {
	Encryption string `json:"encryption"`
	Kvno       int    `json:"kvno"`
	Principal  string `json:"principal"`
}

// Krb5KeytabUpload defines model for Krb5KeytabUpload.
type Krb5KeytabUpload struct {
	// Data Base64-encoded raw keytab bytes (must begin with magic byte 0x05)
	Data []byte `json:"data"`
}

// Krb5Principal defines model for Krb5Principal.
type Krb5Principal struct {
	// Attributes kadmin attribute flags (REQUIRES_PRE_AUTH, ...)
	Attributes *string `json:"attributes,omitempty"`

	// Expiration kadmin-formatted expiration ([never] or RFC date)
	Expiration *string `json:"expiration,omitempty"`

	// Kvno Current key version number
	Kvno *int `json:"kvno,omitempty"`

	// Name Fully-qualified principal (e.g. nfs/host@REALM)
	Name string `json:"name"`
}

// Krb5PrincipalCreate defines model for Krb5PrincipalCreate.
type Krb5PrincipalCreate struct {
	// Name Principal name; realm optional
	Name string `json:"name"`

	// Password Initial password (mutually exclusive with randkey)
	Password *string `json:"password,omitempty"`

	// Randkey Generate a random key (default for service principals)
	Randkey *bool `json:"randkey,omitempty"`
}

// Krb5Realm defines model for Krb5Realm.
type Krb5Realm struct {
	AdminServer   *string  `json:"adminServer,omitempty"`
	DefaultDomain *string  `json:"defaultDomain,omitempty"`
	Kdc           []string `json:"kdc"`
}

// LiveInterface defines model for LiveInterface.
type LiveInterface struct {
	Addresses *[]string `json:"addresses,omitempty"`
	Gateway   *string   `json:"gateway,omitempty"`
	Mac       *string   `json:"mac,omitempty"`
	Name      *string   `json:"name,omitempty"`
	State     *string   `json:"state,omitempty"`

	// Type ether|vlan|bond|bridge
	Type *string `json:"type,omitempty"`
}

// LoadKeyRequest defines model for LoadKeyRequest.
type LoadKeyRequest struct {
	Keylocation *string `json:"keylocation,omitempty"`
	Recursive   *bool   `json:"recursive,omitempty"`
}

// MetadataPatch defines model for MetadataPatch.
type MetadataPatch struct {
	Description *string            `json:"description,omitempty"`
	DisplayName *string            `json:"display_name,omitempty"`
	Tags        *map[string]string `json:"tags,omitempty"`
}

// NetworkBond defines model for NetworkBond.
type NetworkBond struct {
	Address   *string         `json:"address,omitempty"`
	DryRun    *bool           `json:"dryRun,omitempty"`
	Members   []string        `json:"members"`
	MiiMonSec *int            `json:"miiMonSec,omitempty"`
	Mode      NetworkBondMode `json:"mode"`
	Name      string          `json:"name"`
}

// NetworkBondMode defines model for NetworkBond.Mode.
type NetworkBondMode string

// NetworkInterface Envelope used by ListConfigs/GetConfig.
type NetworkInterface struct {
	Bond      *NetworkBond            `json:"bond,omitempty"`
	Interface *NetworkInterfaceConfig `json:"interface,omitempty"`
	Kind      NetworkInterfaceKind    `json:"kind"`
	Name      string                  `json:"name"`
	Vlan      *NetworkVLAN            `json:"vlan,omitempty"`
}

// NetworkInterfaceKind defines model for NetworkInterface.Kind.
type NetworkInterfaceKind string

// NetworkInterfaceConfig defines model for NetworkInterfaceConfig.
type NetworkInterfaceConfig struct {
	Addresses *[]string                   `json:"addresses,omitempty"`
	Dhcp      *NetworkInterfaceConfigDhcp `json:"dhcp,omitempty"`
	Dns       *[]string                   `json:"dns,omitempty"`
	Domains   *[]string                   `json:"domains,omitempty"`
	DryRun    *bool                       `json:"dryRun,omitempty"`
	Gateway   *string                     `json:"gateway,omitempty"`
	LinkLocal *string                     `json:"linkLocal,omitempty"`

	// MatchName [Match] Name= glob (supports * and ?)
	MatchName string `json:"matchName"`
	Mtu       *int   `json:"mtu,omitempty"`
	Name      string `json:"name"`
}

// NetworkInterfaceConfigDhcp defines model for NetworkInterfaceConfig.Dhcp.
type NetworkInterfaceConfigDhcp string

// NetworkVLAN defines model for NetworkVLAN.
type NetworkVLAN struct {
	// Address CIDR
	Address *string `json:"address,omitempty"`
	DryRun  *bool   `json:"dryRun,omitempty"`
	Id      int     `json:"id"`
	Name    string  `json:"name"`
	Parent  string  `json:"parent"`
}

// NfsActiveExport defines model for NfsActiveExport.
type NfsActiveExport struct {
	Client  string `json:"Client"`
	Options string `json:"Options"`
	Path    string `json:"Path"`
}

// NfsClientRule defines model for NfsClientRule.
type NfsClientRule struct {
	// Options Comma-separated NFS export options (e.g. "rw,sync,sec=krb5p")
	Options string `json:"options"`

	// Spec CIDR, IP, "*", or hostname/wildcard pattern
	Spec string `json:"spec"`
}

// NfsExport defines model for NfsExport.
type NfsExport struct {
	Clients []NfsClientRule `json:"clients"`

	// Name Filename-safe identifier (alnum, -, _; 1-64 chars)
	Name string `json:"name"`

	// Path Absolute host path
	Path string `json:"path"`
}

// NvmeofDHChapConfig Per-host DH-HMAC-CHAP (NVMe TP4022) configuration. Secrets must be in "DHHC-1:NN:..." form. Empty fields are left unchanged on PATCH-style updates.
type NvmeofDHChapConfig struct {
	// CtrlKey Controller secret for bidirectional auth
	CtrlKey *string                    `json:"ctrlKey,omitempty"`
	Dhgroup *NvmeofDHChapConfigDhgroup `json:"dhgroup,omitempty"`
	Hash    *NvmeofDHChapConfigHash    `json:"hash,omitempty"`

	// Key Host secret in TP4022 format
	Key *string `json:"key,omitempty"`
}

// NvmeofDHChapConfigDhgroup defines model for NvmeofDHChapConfig.Dhgroup.
type NvmeofDHChapConfigDhgroup string

// NvmeofDHChapConfigHash defines model for NvmeofDHChapConfig.Hash.
type NvmeofDHChapConfigHash string

// NvmeofDHChapDetail Read-side DH-HMAC-CHAP detail. Raw key material is never returned.
type NvmeofDHChapDetail struct {
	Dhgroup    *string `json:"dhgroup,omitempty"`
	HasCtrlKey bool    `json:"hasCtrlKey"`
	HasKey     bool    `json:"hasKey"`
	Hash       *string `json:"hash,omitempty"`
}

// NvmeofHost defines model for NvmeofHost.
type NvmeofHost struct {
	HostNqn string `json:"hostNqn"`
}

// NvmeofNamespace defines model for NvmeofNamespace.
type NvmeofNamespace struct {
	// DevicePath Must start with /dev/
	DevicePath string `json:"devicePath"`
	Enabled    *bool  `json:"enabled,omitempty"`
	Nsid       int    `json:"nsid"`
}

// NvmeofPort defines model for NvmeofPort.
type NvmeofPort struct {
	Id        int                 `json:"id"`
	Ip        string              `json:"ip"`
	Port      int                 `json:"port"`
	Transport NvmeofPortTransport `json:"transport"`
}

// NvmeofPortTransport defines model for NvmeofPort.Transport.
type NvmeofPortTransport string

// NvmeofSubsystem defines model for NvmeofSubsystem.
type NvmeofSubsystem struct {
	AllowAnyHost *bool   `json:"allowAnyHost,omitempty"`
	Nqn          string  `json:"nqn"`
	Serial       *string `json:"serial,omitempty"`
}

// NvmeofSubsystemDetail defines model for NvmeofSubsystemDetail.
type NvmeofSubsystemDetail struct {
	AllowedHosts *[]string          `json:"allowedHosts,omitempty"`
	Namespaces   *[]NvmeofNamespace `json:"namespaces,omitempty"`
	Subsystem    *NvmeofSubsystem   `json:"subsystem,omitempty"`
}

// Pool defines model for Pool.
type Pool struct {
	Allocated        *int    `json:"allocated,omitempty"`
	CapacityPct      *int    `json:"capacityPct,omitempty"`
	DedupRatio       *string `json:"dedupRatio,omitempty"`
	FragmentationPct *int    `json:"fragmentationPct,omitempty"`
	Free             *int    `json:"free,omitempty"`
	Health           *string `json:"health,omitempty"`
	Name             *string `json:"name,omitempty"`
	ReadOnly         *bool   `json:"readOnly,omitempty"`
	SizeBytes        *int    `json:"sizeBytes,omitempty"`
}

// PoolCreateSpec defines model for PoolCreateSpec.
type PoolCreateSpec struct {
	Cache *[]string   `json:"cache,omitempty"`
	Log   *[]VdevSpec `json:"log,omitempty"`
	Name  string      `json:"name"`
	Spare *[]string   `json:"spare,omitempty"`
	Vdevs []VdevSpec  `json:"vdevs"`
}

// PoolDetail defines model for PoolDetail.
type PoolDetail struct {
	Pool       *Pool              `json:"pool,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
	Status     *struct {
		State *string `json:"state,omitempty"`
		Vdevs *[]Vdev `json:"vdevs,omitempty"`
	} `json:"status,omitempty"`
}

// PoolPropertiesPatch defines model for PoolPropertiesPatch.
type PoolPropertiesPatch struct {
	Properties map[string]string `json:"properties"`
}

// PoolSyncRequest defines model for PoolSyncRequest.
type PoolSyncRequest struct {
	// Names Pool names to sync; empty/omitted means all pools.
	Names *[]string `json:"names,omitempty"`
}

// PoolTrimRequest defines model for PoolTrimRequest.
type PoolTrimRequest struct {
	// Disk Optional vdev path; absent trims the whole pool
	Disk *string `json:"disk,omitempty"`
}

// Protocol defines model for Protocol.
type Protocol string

// ProtocolNFSOpts defines model for ProtocolNFSOpts.
type ProtocolNFSOpts struct {
	Clients []NfsClientRule `json:"clients"`
}

// ProtocolSMBOpts defines model for ProtocolSMBOpts.
type ProtocolSMBOpts struct {
	Browseable *bool     `json:"browseable,omitempty"`
	Comment    *string   `json:"comment,omitempty"`
	GuestOk    *bool     `json:"guestOk,omitempty"`
	ValidUsers *[]string `json:"validUsers,omitempty"`
	WriteList  *[]string `json:"writeList,omitempty"`
}

// ProtocolShare defines model for ProtocolShare.
type ProtocolShare struct {
	Acls        []DatasetACE `json:"acls"`
	DatasetName string       `json:"datasetName"`

	// Name 1-64 alnum/-/_ identifier.
	Name       string           `json:"name"`
	Nfs        *ProtocolNFSOpts `json:"nfs,omitempty"`
	Pool       string           `json:"pool"`
	Protocols  []Protocol       `json:"protocols"`
	QuotaBytes *int64           `json:"quotaBytes,omitempty"`
	Smb        *ProtocolSMBOpts `json:"smb,omitempty"`
}

// ProtocolShareDetail defines model for ProtocolShareDetail.
type ProtocolShareDetail struct {
	Acl             []DatasetACE     `json:"acl"`
	Path            string           `json:"path"`
	ProtocolsStatus []ProtocolStatus `json:"protocolsStatus"`
	Share           ProtocolShare    `json:"share"`
}

// ProtocolStatus defines model for ProtocolStatus.
type ProtocolStatus struct {
	Active   bool     `json:"active"`
	Detail   *string  `json:"detail,omitempty"`
	Protocol Protocol `json:"protocol"`
}

// RdmaAdapter defines model for RdmaAdapter.
type RdmaAdapter struct {
	BoardId *string `json:"boardId,omitempty"`
	HcaType *string `json:"hcaType,omitempty"`

	// Name e.g. mlx5_0
	Name  string             `json:"name"`
	Ports *[]RdmaAdapterPort `json:"ports,omitempty"`
}

// RdmaAdapterPort defines model for RdmaAdapterPort.
type RdmaAdapterPort struct {
	Gids *[]string `json:"gids,omitempty"`

	// LinkLayer InfiniBand or Ethernet (RoCE)
	LinkLayer string `json:"linkLayer"`
	Number    int    `json:"number"`

	// State ACTIVE, DOWN, INIT, ARMED
	State string `json:"state"`
}

// ReplicationSchedule defines model for ReplicationSchedule.
type ReplicationSchedule struct {
	Cron            *string             `json:"cron,omitempty"`
	Enabled         *bool               `json:"enabled,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	RetentionRemote *int                `json:"retentionRemote,omitempty"`
	SnapshotPrefix  *string             `json:"snapshotPrefix,omitempty"`
	SrcDataset      *string             `json:"srcDataset,omitempty"`
	TargetId        *openapi_types.UUID `json:"targetId,omitempty"`
}

// ReplicationTarget defines model for ReplicationTarget.
type ReplicationTarget struct {
	DatasetPrefix *string             `json:"datasetPrefix,omitempty"`
	Host          *string             `json:"host,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	Name          *string             `json:"name,omitempty"`
	Port          *int                `json:"port,omitempty"`
	SshKeyPath    *string             `json:"sshKeyPath,omitempty"`
	SshUser       *string             `json:"sshUser,omitempty"`
}

// ResourceMetadata defines model for ResourceMetadata.
type ResourceMetadata struct {
	Description *string            `json:"description,omitempty"`
	DisplayName *string            `json:"displayName,omitempty"`
	Id          *int               `json:"id,omitempty"`
	Kind        *string            `json:"kind,omitempty"`
	Tags        *map[string]string `json:"tags,omitempty"`
	ZfsName     *string            `json:"zfsName,omitempty"`
}

// SMTPConfig Outbound SMTP relay configuration. The `password` field is
// write-only — GET responses always return `"***"`. To preserve
// the stored password during a PUT, send the literal string
// `"***"` for `password`; any other non-empty value replaces it.
type SMTPConfig struct {
	FromAddress openapi_types.Email `json:"fromAddress"`

	// Host SMTP relay hostname (e.g. smtp.sendgrid.net).
	Host string `json:"host"`

	// MaxPerMinute Per-recipient leaky-bucket rate limit. Default 30.
	MaxPerMinute *int `json:"maxPerMinute,omitempty"`

	// Password Cleartext on PUT, redacted on GET.
	Password *string `json:"password,omitempty"`
	Port     int     `json:"port"`

	// TlsMode STARTTLS is recommended for port 587; tls (implicit TLS) for port 465.
	TlsMode  SMTPConfigTlsMode `json:"tlsMode"`
	Username *string           `json:"username,omitempty"`
}

// SMTPConfigTlsMode STARTTLS is recommended for port 587; tls (implicit TLS) for port 465.
type SMTPConfigTlsMode string

// SambaGlobalsOpts defines model for SambaGlobalsOpts.
type SambaGlobalsOpts struct {
	// AclProfile Default nfsv4. Selects vfs_zfsacl vs acl_xattr.
	AclProfile    *SambaGlobalsOptsAclProfile `json:"aclProfile,omitempty"`
	CustomLines   *[]string                   `json:"customLines,omitempty"`
	EnableNetbios *bool                       `json:"enableNetbios,omitempty"`

	// Realm Required when securityMode=ads.
	Realm        *string                       `json:"realm,omitempty"`
	SecurityMode *SambaGlobalsOptsSecurityMode `json:"securityMode,omitempty"`

	// ServerString Default NovaNAS
	ServerString *string `json:"serverString,omitempty"`

	// Workgroup Default WORKGROUP
	Workgroup *string `json:"workgroup,omitempty"`
}

// SambaGlobalsOptsAclProfile Default nfsv4. Selects vfs_zfsacl vs acl_xattr.
type SambaGlobalsOptsAclProfile string

// SambaGlobalsOptsSecurityMode defines model for SambaGlobalsOpts.SecurityMode.
type SambaGlobalsOptsSecurityMode string

// SambaShare defines model for SambaShare.
type SambaShare struct {
	AdminUsers    *[]string `json:"adminUsers,omitempty"`
	Browseable    *bool     `json:"browseable,omitempty"`
	Comment       *string   `json:"comment,omitempty"`
	CreateMask    *string   `json:"createMask,omitempty"`
	DirectoryMask *string   `json:"directoryMask,omitempty"`
	GuestOk       *bool     `json:"guestOk,omitempty"`
	Name          string    `json:"name"`

	// Path Absolute path on the host
	Path       string    `json:"path"`
	ReadOnly   *bool     `json:"readOnly,omitempty"`
	ValidUsers *[]string `json:"validUsers,omitempty"`
	Veto       *[]string `json:"veto,omitempty"`
	Writable   *bool     `json:"writable,omitempty"`
	WriteList  *[]string `json:"writeList,omitempty"`
}

// SambaUser defines model for SambaUser.
type SambaUser struct {
	Username string `json:"username"`
}

// SambaUserCredentials defines model for SambaUserCredentials.
type SambaUserCredentials struct {
	Password string `json:"password"`

	// Username Required on POST /samba/users; ignored on PUT password.
	Username *string `json:"username,omitempty"`
}

// ScrubPolicy defines model for ScrubPolicy.
type ScrubPolicy struct {
	// Builtin true for the operator-default policy installed on a fresh install.
	Builtin *bool `json:"builtin,omitempty"`

	// Cron Standard 5-field cron expression
	Cron        *string             `json:"cron,omitempty"`
	Enabled     *bool               `json:"enabled,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	LastError   *string             `json:"lastError,omitempty"`
	LastFiredAt *time.Time          `json:"lastFiredAt,omitempty"`
	Name        *string             `json:"name,omitempty"`

	// Pools Either "*" (all pools at fire time) or a comma-separated list of pool names.
	Pools    *string              `json:"pools,omitempty"`
	Priority *ScrubPolicyPriority `json:"priority,omitempty"`
}

// ScrubPolicyPriority defines model for ScrubPolicy.Priority.
type ScrubPolicyPriority string

// SmartAttribute defines model for SmartAttribute.
type SmartAttribute struct {
	Id         *int    `json:"id,omitempty"`
	Name       *string `json:"name,omitempty"`
	RawValue   *string `json:"rawValue,omitempty"`
	Threshold  *int    `json:"threshold,omitempty"`
	Value      *int    `json:"value,omitempty"`
	WhenFailed *string `json:"whenFailed,omitempty"`
	Worst      *int    `json:"worst,omitempty"`
}

// SmartHealth defines model for SmartHealth.
type SmartHealth struct {
	Attributes    *[]SmartAttribute `json:"attributes,omitempty"`
	CapacityBytes *int64            `json:"capacityBytes,omitempty"`
	DeviceName    *string           `json:"deviceName,omitempty"`
	ErrorSummary  *[]string         `json:"errorSummary,omitempty"`
	Firmware      *string           `json:"firmware,omitempty"`
	HasErrors     *bool             `json:"hasErrors,omitempty"`
	LastTest      *SmartSelfTest    `json:"lastTest,omitempty"`
	Model         *string           `json:"model,omitempty"`
	OverallPassed *bool             `json:"overallPassed,omitempty"`
	PowerCycles   *int              `json:"powerCycles,omitempty"`
	PowerOnHours  *int              `json:"powerOnHours,omitempty"`
	SerialNumber  *string           `json:"serialNumber,omitempty"`
	TemperatureC  *int              `json:"temperatureC,omitempty"`
}

// SmartSelfTest defines model for SmartSelfTest.
type SmartSelfTest struct {
	LbaOfFirstError *int64  `json:"lbaOfFirstError,omitempty"`
	LifetimeHours   *int    `json:"lifetimeHours,omitempty"`
	Status          *string `json:"status,omitempty"`
	Type            *string `json:"type,omitempty"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	CreationUnix    *int    `json:"creationUnix,omitempty"`
	Dataset         *string `json:"dataset,omitempty"`
	Name            *string `json:"name,omitempty"`
	ReferencedBytes *int    `json:"referencedBytes,omitempty"`
	ShortName       *string `json:"shortName,omitempty"`
	UsedBytes       *int    `json:"usedBytes,omitempty"`
}

// SnapshotHoldRequest defines model for SnapshotHoldRequest.
type SnapshotHoldRequest struct {
	Recursive *bool  `json:"recursive,omitempty"`
	Tag       string `json:"tag"`
}

// SnapshotReleaseRequest defines model for SnapshotReleaseRequest.
type SnapshotReleaseRequest struct {
	Recursive *bool  `json:"recursive,omitempty"`
	Tag       string `json:"tag"`
}

// SnapshotSchedule defines model for SnapshotSchedule.
type SnapshotSchedule struct {
	// Cron Standard 5-field cron expression
	Cron             *string             `json:"cron,omitempty"`
	Dataset          *string             `json:"dataset,omitempty"`
	Enabled          *bool               `json:"enabled,omitempty"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	Name             *string             `json:"name,omitempty"`
	Recursive        *bool               `json:"recursive,omitempty"`
	RetentionDaily   *int                `json:"retentionDaily,omitempty"`
	RetentionHourly  *int                `json:"retentionHourly,omitempty"`
	RetentionMonthly *int                `json:"retentionMonthly,omitempty"`
	RetentionWeekly  *int                `json:"retentionWeekly,omitempty"`
	RetentionYearly  *int                `json:"retentionYearly,omitempty"`
	SnapshotPrefix   *string             `json:"snapshotPrefix,omitempty"`
}

// SystemCPUInfo defines model for SystemCPUInfo.
type SystemCPUInfo struct {
	Cores   *int    `json:"cores,omitempty"`
	Model   *string `json:"model,omitempty"`
	Sockets *int    `json:"sockets,omitempty"`
	Threads *int    `json:"threads,omitempty"`
}

// SystemHostnameRequest defines model for SystemHostnameRequest.
type SystemHostnameRequest struct {
	Hostname string `json:"hostname"`
}

// SystemInfo defines model for SystemInfo.
type SystemInfo struct {
	Architecture  *string            `json:"architecture,omitempty"`
	Cpu           *SystemCPUInfo     `json:"cpu,omitempty"`
	Hostname      *string            `json:"hostname,omitempty"`
	KernelRelease *string            `json:"kernelRelease,omitempty"`
	LoadAvg       *[]float32         `json:"loadAvg,omitempty"`
	Memory        *SystemMemoryStats `json:"memory,omitempty"`
	OsPretty      *string            `json:"osPretty,omitempty"`

	// Uptime Go duration string (e.g. 1h2m3s)
	Uptime     *string `json:"uptime,omitempty"`
	ZfsVersion *string `json:"zfsVersion,omitempty"`
}

// SystemMemoryStats defines model for SystemMemoryStats.
type SystemMemoryStats struct {
	AvailableKB *int64 `json:"availableKB,omitempty"`
	SwapFreeKB  *int64 `json:"swapFreeKB,omitempty"`
	SwapTotalKB *int64 `json:"swapTotalKB,omitempty"`
	TotalKB     *int64 `json:"totalKB,omitempty"`
}

// SystemNTPRequest defines model for SystemNTPRequest.
type SystemNTPRequest struct {
	Enabled bool      `json:"enabled"`
	Servers *[]string `json:"servers,omitempty"`
}

// SystemTimeConfig defines model for SystemTimeConfig.
type SystemTimeConfig struct {
	Ntp          *bool     `json:"ntp,omitempty"`
	NtpServers   *[]string `json:"ntpServers,omitempty"`
	Synchronized *bool     `json:"synchronized,omitempty"`
	Timezone     *string   `json:"timezone,omitempty"`
}

// SystemTimezoneRequest defines model for SystemTimezoneRequest.
type SystemTimezoneRequest struct {
	// Timezone IANA zoneinfo name (e.g. Europe/Brussels)
	Timezone string `json:"timezone"`
}

// Vdev defines model for Vdev.
type Vdev struct {
	ChecksumErrors *int    `json:"checksumErrors,omitempty"`
	Children       *[]Vdev `json:"children,omitempty"`
	Path           *string `json:"path,omitempty"`
	ReadErrors     *int    `json:"readErrors,omitempty"`
	State          *string `json:"state,omitempty"`
	Type           *string `json:"type,omitempty"`
	WriteErrors    *int    `json:"writeErrors,omitempty"`
}

// VdevSpec defines model for VdevSpec.
type VdevSpec struct {
	Disks []string     `json:"disks"`
	Type  VdevSpecType `json:"type"`
}

// VdevSpecType defines model for VdevSpec.Type.
type VdevSpecType string

// Accepted defines model for Accepted.
type Accepted struct {
	JobId *openapi_types.UUID `json:"jobId,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListAuditParams defines parameters for ListAudit.
type ListAuditParams struct {
	Actor  *string `form:"actor,omitempty" json:"actor,omitempty"`
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// Resource Prefix-matched against the event's resource path.
	Resource *string                 `form:"resource,omitempty" json:"resource,omitempty"`
	Outcome  *ListAuditParamsOutcome `form:"outcome,omitempty" json:"outcome,omitempty"`
	Since    *time.Time              `form:"since,omitempty" json:"since,omitempty"`
	Until    *time.Time              `form:"until,omitempty" json:"until,omitempty"`

	// SourceIp IP or CIDR; matched against payload->>'source_ip'.
	SourceIp *string `form:"source_ip,omitempty" json:"source_ip,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor   *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListAuditParamsOutcome defines parameters for ListAudit.
type ListAuditParamsOutcome string

// ExportAuditParams defines parameters for ExportAudit.
type ExportAuditParams struct {
	Format   *ExportAuditParamsFormat  `form:"format,omitempty" json:"format,omitempty"`
	Actor    *string                   `form:"actor,omitempty" json:"actor,omitempty"`
	Action   *string                   `form:"action,omitempty" json:"action,omitempty"`
	Resource *string                   `form:"resource,omitempty" json:"resource,omitempty"`
	Outcome  *ExportAuditParamsOutcome `form:"outcome,omitempty" json:"outcome,omitempty"`
	Since    *time.Time                `form:"since,omitempty" json:"since,omitempty"`
	Until    *time.Time                `form:"until,omitempty" json:"until,omitempty"`
	SourceIp *string                   `form:"source_ip,omitempty" json:"source_ip,omitempty"`
}

// ExportAuditParamsFormat defines parameters for ExportAudit.
type ExportAuditParamsFormat string

// ExportAuditParamsOutcome defines parameters for ExportAudit.
type ExportAuditParamsOutcome string

// SummarizeAuditParams defines parameters for SummarizeAudit.
type SummarizeAuditParams struct {
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Until *time.Time `form:"until,omitempty" json:"until,omitempty"`
}

// ListDatasetsParams defines parameters for ListDatasets.
type ListDatasetsParams struct {
	Pool *string `form:"pool,omitempty" json:"pool,omitempty"`
}

// DestroyDatasetParams defines parameters for DestroyDataset.
type DestroyDatasetParams struct {
	Recursive *bool `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// PatchDatasetPropsJSONBody defines parameters for PatchDatasetProps.
type PatchDatasetPropsJSONBody struct {
	Properties map[string]string `json:"properties"`
}

// DiffDatasetParams defines parameters for DiffDataset.
type DiffDatasetParams struct {
	To *string `form:"to,omitempty" json:"to,omitempty"`
}

// ReceiveDatasetParams defines parameters for ReceiveDataset.
type ReceiveDatasetParams struct {
	Force     *bool   `form:"force,omitempty" json:"force,omitempty"`
	Resumable *bool   `form:"resumable,omitempty" json:"resumable,omitempty"`
	Origin    *string `form:"origin,omitempty" json:"origin,omitempty"`
}

// RollbackDatasetJSONBody defines parameters for RollbackDataset.
type RollbackDatasetJSONBody struct {
	Snapshot string `json:"snapshot"`
}

// SendDatasetParams defines parameters for SendDataset.
type SendDatasetParams struct {
	Recursive    *bool   `form:"recursive,omitempty" json:"recursive,omitempty"`
	Raw          *bool   `form:"raw,omitempty" json:"raw,omitempty"`
	Compressed   *bool   `form:"compressed,omitempty" json:"compressed,omitempty"`
	LargeBlock   *bool   `form:"largeBlock,omitempty" json:"largeBlock,omitempty"`
	EmbeddedData *bool   `form:"embeddedData,omitempty" json:"embeddedData,omitempty"`
	From         *string `form:"from,omitempty" json:"from,omitempty"`
}

// UnloadDatasetKeyJSONBody defines parameters for UnloadDatasetKey.
type UnloadDatasetKeyJSONBody struct {
	Recursive *bool `json:"recursive,omitempty"`
}

// RunDiskSmartTestParams defines parameters for RunDiskSmartTest.
type RunDiskSmartTestParams struct {
	Type string `form:"type" json:"type"`
}

// CreateIscsiTargetJSONBody defines parameters for CreateIscsiTarget.
type CreateIscsiTargetJSONBody struct {
	Iqn string `json:"iqn"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	State  *ListJobsParamsState `form:"state,omitempty" json:"state,omitempty"`
	Limit  *int                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListJobsParamsState defines parameters for ListJobs.
type ListJobsParamsState string

// ApplyNetworkBondParams defines parameters for ApplyNetworkBond.
type ApplyNetworkBondParams struct {
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// ApplyNetworkInterfaceConfigParams defines parameters for ApplyNetworkInterfaceConfig.
type ApplyNetworkInterfaceConfigParams struct {
	// Force Bypass the management-interface guard. Required when the request would touch the iface owning the request's source IP, or when the source IP cannot be verified.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// DeleteNetworkConfigParams defines parameters for DeleteNetworkConfig.
type DeleteNetworkConfigParams struct {
	// Force Bypass management-interface guard.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// NetworkReloadParams defines parameters for NetworkReload.
type NetworkReloadParams struct {
	Force bool `form:"force" json:"force"`
}

// ApplyNetworkVLANParams defines parameters for ApplyNetworkVLAN.
type ApplyNetworkVLANParams struct {
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// SendSMTPTestJSONBody defines parameters for SendSMTPTest.
type SendSMTPTestJSONBody struct {
	To openapi_types.Email `json:"to"`
}

// LinkNvmeofSubsystemJSONBody defines parameters for LinkNvmeofSubsystem.
type LinkNvmeofSubsystemJSONBody struct {
	Nqn string `json:"nqn"`
}

// ScrubPoolParams defines parameters for ScrubPool.
type ScrubPoolParams struct {
	Action *string `form:"action,omitempty" json:"action,omitempty"`
}

// TrimPoolParams defines parameters for TrimPool.
type TrimPoolParams struct {
	Action *string `form:"action,omitempty" json:"action,omitempty"`
}

// UpgradePoolParams defines parameters for UpgradePool.
type UpgradePoolParams struct {
	// All When true, upgrade all pools (`zpool upgrade -a`); the path name is ignored.
	All *bool `form:"all,omitempty" json:"all,omitempty"`
}

// WaitPoolParams defines parameters for WaitPool.
type WaitPoolParams struct {
	Activity   string `form:"activity" json:"activity"`
	TimeoutSec *int   `form:"timeoutSec,omitempty" json:"timeoutSec,omitempty"`
}

// DeleteProtocolShareParams defines parameters for DeleteProtocolShare.
type DeleteProtocolShareParams struct {
	Pool    *string `form:"pool,omitempty" json:"pool,omitempty"`
	Dataset *string `form:"dataset,omitempty" json:"dataset,omitempty"`
}

// GetProtocolShareParams defines parameters for GetProtocolShare.
type GetProtocolShareParams struct {
	Pool    string `form:"pool" json:"pool"`
	Dataset string `form:"dataset" json:"dataset"`
}

// ListSnapshotsParams defines parameters for ListSnapshots.
type ListSnapshotsParams struct {
	Dataset *string `form:"dataset,omitempty" json:"dataset,omitempty"`
}

// CreateSnapshotJSONBody defines parameters for CreateSnapshot.
type CreateSnapshotJSONBody struct {
	Dataset   string `json:"dataset"`
	Name      string `json:"name"`
	Recursive *bool  `json:"recursive,omitempty"`
}

// SystemRebootParams defines parameters for SystemReboot.
type SystemRebootParams struct {
	// DelaySec Delay in seconds before reboot. 0 (default) means immediate (--no-block); >0 schedules `shutdown -r +<min>` rounded up.
	DelaySec *int `form:"delaySec,omitempty" json:"delaySec,omitempty"`
}

// SystemShutdownParams defines parameters for SystemShutdown.
type SystemShutdownParams struct {
	DelaySec *int `form:"delaySec,omitempty" json:"delaySec,omitempty"`
}

// CreateDatasetJSONRequestBody defines body for CreateDataset for application/json ContentType.
type CreateDatasetJSONRequestBody = DatasetCreateSpec

// PatchDatasetPropsJSONRequestBody defines body for PatchDatasetProps for application/json ContentType.
type PatchDatasetPropsJSONRequestBody PatchDatasetPropsJSONBody

// SetDatasetACLJSONRequestBody defines body for SetDatasetACL for application/json ContentType.
type SetDatasetACLJSONRequestBody = DatasetACLSetRequest

// AppendDatasetACEJSONRequestBody defines body for AppendDatasetACE for application/json ContentType.
type AppendDatasetACEJSONRequestBody = DatasetACLAppendRequest

// BookmarkSnapshotJSONRequestBody defines body for BookmarkSnapshot for application/json ContentType.
type BookmarkSnapshotJSONRequestBody = DatasetBookmarkRequest

// ChangeDatasetKeyJSONRequestBody defines body for ChangeDatasetKey for application/json ContentType.
type ChangeDatasetKeyJSONRequestBody = ChangeKeyRequest

// CloneDatasetJSONRequestBody defines body for CloneDataset for application/json ContentType.
type CloneDatasetJSONRequestBody = DatasetCloneRequest

// DestroyDatasetBookmarkJSONRequestBody defines body for DestroyDatasetBookmark for application/json ContentType.
type DestroyDatasetBookmarkJSONRequestBody = BookmarkDestroyRequest

// LoadDatasetKeyJSONRequestBody defines body for LoadDatasetKey for application/json ContentType.
type LoadDatasetKeyJSONRequestBody = LoadKeyRequest

// PatchDatasetMetadataJSONRequestBody defines body for PatchDatasetMetadata for application/json ContentType.
type PatchDatasetMetadataJSONRequestBody = MetadataPatch

// RenameDatasetJSONRequestBody defines body for RenameDataset for application/json ContentType.
type RenameDatasetJSONRequestBody = DatasetRenameRequest

// RollbackDatasetJSONRequestBody defines body for RollbackDataset for application/json ContentType.
type RollbackDatasetJSONRequestBody RollbackDatasetJSONBody

// UnloadDatasetKeyJSONRequestBody defines body for UnloadDatasetKey for application/json ContentType.
type UnloadDatasetKeyJSONRequestBody UnloadDatasetKeyJSONBody

// CreateIscsiTargetJSONRequestBody defines body for CreateIscsiTarget for application/json ContentType.
type CreateIscsiTargetJSONRequestBody CreateIscsiTargetJSONBody

// CreateIscsiACLJSONRequestBody defines body for CreateIscsiACL for application/json ContentType.
type CreateIscsiACLJSONRequestBody = IscsiACL

// CreateIscsiLUNJSONRequestBody defines body for CreateIscsiLUN for application/json ContentType.
type CreateIscsiLUNJSONRequestBody = IscsiLUN

// CreateIscsiPortalJSONRequestBody defines body for CreateIscsiPortal for application/json ContentType.
type CreateIscsiPortalJSONRequestBody = IscsiPortal

// SetKrb5ConfigJSONRequestBody defines body for SetKrb5Config for application/json ContentType.
type SetKrb5ConfigJSONRequestBody = Krb5Config

// SetKrb5IdmapdJSONRequestBody defines body for SetKrb5Idmapd for application/json ContentType.
type SetKrb5IdmapdJSONRequestBody = Krb5IdmapdConfig

// UploadKrb5KeytabJSONRequestBody defines body for UploadKrb5Keytab for application/json ContentType.
type UploadKrb5KeytabJSONRequestBody = Krb5KeytabUpload

// CreateKrb5PrincipalJSONRequestBody defines body for CreateKrb5Principal for application/json ContentType.
type CreateKrb5PrincipalJSONRequestBody = Krb5PrincipalCreate

// ApplyNetworkBondJSONRequestBody defines body for ApplyNetworkBond for application/json ContentType.
type ApplyNetworkBondJSONRequestBody = NetworkBond

// ApplyNetworkInterfaceConfigJSONRequestBody defines body for ApplyNetworkInterfaceConfig for application/json ContentType.
type ApplyNetworkInterfaceConfigJSONRequestBody = NetworkInterfaceConfig

// ApplyNetworkVLANJSONRequestBody defines body for ApplyNetworkVLAN for application/json ContentType.
type ApplyNetworkVLANJSONRequestBody = NetworkVLAN

// CreateNfsExportJSONRequestBody defines body for CreateNfsExport for application/json ContentType.
type CreateNfsExportJSONRequestBody = NfsExport

// UpdateNfsExportJSONRequestBody defines body for UpdateNfsExport for application/json ContentType.
type UpdateNfsExportJSONRequestBody = NfsExport

// PutSMTPConfigJSONRequestBody defines body for PutSMTPConfig for application/json ContentType.
type PutSMTPConfigJSONRequestBody = SMTPConfig

// SendSMTPTestJSONRequestBody defines body for SendSMTPTest for application/json ContentType.
type SendSMTPTestJSONRequestBody SendSMTPTestJSONBody

// SetNvmeofHostDHChapJSONRequestBody defines body for SetNvmeofHostDHChap for application/json ContentType.
type SetNvmeofHostDHChapJSONRequestBody = NvmeofDHChapConfig

// CreateNvmeofPortJSONRequestBody defines body for CreateNvmeofPort for application/json ContentType.
type CreateNvmeofPortJSONRequestBody = NvmeofPort

// LinkNvmeofSubsystemJSONRequestBody defines body for LinkNvmeofSubsystem for application/json ContentType.
type LinkNvmeofSubsystemJSONRequestBody LinkNvmeofSubsystemJSONBody

// CreateNvmeofSubsystemJSONRequestBody defines body for CreateNvmeofSubsystem for application/json ContentType.
type CreateNvmeofSubsystemJSONRequestBody = NvmeofSubsystem

// AllowNvmeofHostJSONRequestBody defines body for AllowNvmeofHost for application/json ContentType.
type AllowNvmeofHostJSONRequestBody = NvmeofHost

// AddNvmeofNamespaceJSONRequestBody defines body for AddNvmeofNamespace for application/json ContentType.
type AddNvmeofNamespaceJSONRequestBody = NvmeofNamespace

// CreatePoolJSONRequestBody defines body for CreatePool for application/json ContentType.
type CreatePoolJSONRequestBody = PoolCreateSpec

// SyncPoolsJSONRequestBody defines body for SyncPools for application/json ContentType.
type SyncPoolsJSONRequestBody = PoolSyncRequest

// PatchPoolMetadataJSONRequestBody defines body for PatchPoolMetadata for application/json ContentType.
type PatchPoolMetadataJSONRequestBody = MetadataPatch

// PatchPoolPropertiesJSONRequestBody defines body for PatchPoolProperties for application/json ContentType.
type PatchPoolPropertiesJSONRequestBody = PoolPropertiesPatch

// TrimPoolJSONRequestBody defines body for TrimPool for application/json ContentType.
type TrimPoolJSONRequestBody = PoolTrimRequest

// CreateProtocolShareJSONRequestBody defines body for CreateProtocolShare for application/json ContentType.
type CreateProtocolShareJSONRequestBody = ProtocolShare

// UpdateProtocolShareJSONRequestBody defines body for UpdateProtocolShare for application/json ContentType.
type UpdateProtocolShareJSONRequestBody = ProtocolShare

// SetSambaGlobalsJSONRequestBody defines body for SetSambaGlobals for application/json ContentType.
type SetSambaGlobalsJSONRequestBody = SambaGlobalsOpts

// CreateSambaShareJSONRequestBody defines body for CreateSambaShare for application/json ContentType.
type CreateSambaShareJSONRequestBody = SambaShare

// UpdateSambaShareJSONRequestBody defines body for UpdateSambaShare for application/json ContentType.
type UpdateSambaShareJSONRequestBody = SambaShare

// AddSambaUserJSONRequestBody defines body for AddSambaUser for application/json ContentType.
type AddSambaUserJSONRequestBody = SambaUserCredentials

// SetSambaUserPasswordJSONRequestBody defines body for SetSambaUserPassword for application/json ContentType.
type SetSambaUserPasswordJSONRequestBody = SambaUserCredentials

// CreateReplicationScheduleJSONRequestBody defines body for CreateReplicationSchedule for application/json ContentType.
type CreateReplicationScheduleJSONRequestBody = ReplicationSchedule

// UpdateReplicationScheduleJSONRequestBody defines body for UpdateReplicationSchedule for application/json ContentType.
type UpdateReplicationScheduleJSONRequestBody = ReplicationSchedule

// CreateReplicationTargetJSONRequestBody defines body for CreateReplicationTarget for application/json ContentType.
type CreateReplicationTargetJSONRequestBody = ReplicationTarget

// CreateSnapshotScheduleJSONRequestBody defines body for CreateSnapshotSchedule for application/json ContentType.
type CreateSnapshotScheduleJSONRequestBody = SnapshotSchedule

// UpdateSnapshotScheduleJSONRequestBody defines body for UpdateSnapshotSchedule for application/json ContentType.
type UpdateSnapshotScheduleJSONRequestBody = SnapshotSchedule

// CreateScrubPolicyJSONRequestBody defines body for CreateScrubPolicy for application/json ContentType.
type CreateScrubPolicyJSONRequestBody = ScrubPolicy

// UpdateScrubPolicyJSONRequestBody defines body for UpdateScrubPolicy for application/json ContentType.
type UpdateScrubPolicyJSONRequestBody = ScrubPolicy

// CreateSnapshotJSONRequestBody defines body for CreateSnapshot for application/json ContentType.
type CreateSnapshotJSONRequestBody CreateSnapshotJSONBody

// HoldSnapshotJSONRequestBody defines body for HoldSnapshot for application/json ContentType.
type HoldSnapshotJSONRequestBody = SnapshotHoldRequest

// PatchSnapshotMetadataJSONRequestBody defines body for PatchSnapshotMetadata for application/json ContentType.
type PatchSnapshotMetadataJSONRequestBody = MetadataPatch

// ReleaseSnapshotJSONRequestBody defines body for ReleaseSnapshot for application/json ContentType.
type ReleaseSnapshotJSONRequestBody = SnapshotReleaseRequest

// SetSystemHostnameJSONRequestBody defines body for SetSystemHostname for application/json ContentType.
type SetSystemHostnameJSONRequestBody = SystemHostnameRequest

// SetSystemNTPJSONRequestBody defines body for SetSystemNTP for application/json ContentType.
type SetSystemNTPJSONRequestBody = SystemNTPRequest

// SetSystemTimezoneJSONRequestBody defines body for SetSystemTimezone for application/json ContentType.
type SetSystemTimezoneJSONRequestBody = SystemTimezoneRequest
