// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DatasetType.
const (
	DatasetTypeFilesystem DatasetType = "filesystem"
	DatasetTypeVolume     DatasetType = "volume"
)

// Valid indicates whether the value is a known member of the DatasetType enum.
func (e DatasetType) Valid() bool {
	switch e {
	case DatasetTypeFilesystem:
		return true
	case DatasetTypeVolume:
		return true
	default:
		return false
	}
}

// Defines values for DatasetCreateSpecType.
const (
	DatasetCreateSpecTypeFilesystem DatasetCreateSpecType = "filesystem"
	DatasetCreateSpecTypeVolume     DatasetCreateSpecType = "volume"
)

// Valid indicates whether the value is a known member of the DatasetCreateSpecType enum.
func (e DatasetCreateSpecType) Valid() bool {
	switch e {
	case DatasetCreateSpecTypeFilesystem:
		return true
	case DatasetCreateSpecTypeVolume:
		return true
	default:
		return false
	}
}

// Defines values for DatasetDiffEntryChange.
const (
	M     DatasetDiffEntryChange = "M"
	Minus DatasetDiffEntryChange = "-"
	Plus  DatasetDiffEntryChange = "+"
	R     DatasetDiffEntryChange = "R"
)

// Valid indicates whether the value is a known member of the DatasetDiffEntryChange enum.
func (e DatasetDiffEntryChange) Valid() bool {
	switch e {
	case M:
		return true
	case Minus:
		return true
	case Plus:
		return true
	case R:
		return true
	default:
		return false
	}
}

// Defines values for IscsiPortalTransport.
const (
	IscsiPortalTransportIser IscsiPortalTransport = "iser"
	IscsiPortalTransportTcp  IscsiPortalTransport = "tcp"
)

// Valid indicates whether the value is a known member of the IscsiPortalTransport enum.
func (e IscsiPortalTransport) Valid() bool {
	switch e {
	case IscsiPortalTransportIser:
		return true
	case IscsiPortalTransportTcp:
		return true
	default:
		return false
	}
}

// Defines values for NvmeofDHChapConfigDhgroup.
const (
	Ffdhe2048   NvmeofDHChapConfigDhgroup = "ffdhe2048"
	Ffdhe3072   NvmeofDHChapConfigDhgroup = "ffdhe3072"
	Ffdhe4096   NvmeofDHChapConfigDhgroup = "ffdhe4096"
	Ffdhe6144   NvmeofDHChapConfigDhgroup = "ffdhe6144"
	Ffdhe8192   NvmeofDHChapConfigDhgroup = "ffdhe8192"
	LessThannil NvmeofDHChapConfigDhgroup = "<nil>"
)

// Valid indicates whether the value is a known member of the NvmeofDHChapConfigDhgroup enum.
func (e NvmeofDHChapConfigDhgroup) Valid() bool {
	switch e {
	case Ffdhe2048:
		return true
	case Ffdhe3072:
		return true
	case Ffdhe4096:
		return true
	case Ffdhe6144:
		return true
	case Ffdhe8192:
		return true
	case LessThannil:
		return true
	default:
		return false
	}
}

// Defines values for NvmeofDHChapConfigHash.
const (
	HmacSha256 NvmeofDHChapConfigHash = "hmac(sha256)"
	HmacSha384 NvmeofDHChapConfigHash = "hmac(sha384)"
	HmacSha512 NvmeofDHChapConfigHash = "hmac(sha512)"
)

// Valid indicates whether the value is a known member of the NvmeofDHChapConfigHash enum.
func (e NvmeofDHChapConfigHash) Valid() bool {
	switch e {
	case HmacSha256:
		return true
	case HmacSha384:
		return true
	case HmacSha512:
		return true
	default:
		return false
	}
}

// Defines values for NvmeofPortTransport.
const (
	NvmeofPortTransportRdma NvmeofPortTransport = "rdma"
	NvmeofPortTransportTcp  NvmeofPortTransport = "tcp"
)

// Valid indicates whether the value is a known member of the NvmeofPortTransport enum.
func (e NvmeofPortTransport) Valid() bool {
	switch e {
	case NvmeofPortTransportRdma:
		return true
	case NvmeofPortTransportTcp:
		return true
	default:
		return false
	}
}

// Defines values for VdevSpecType.
const (
	VdevSpecTypeDisk   VdevSpecType = "disk"
	VdevSpecTypeMirror VdevSpecType = "mirror"
	VdevSpecTypeRaidz1 VdevSpecType = "raidz1"
	VdevSpecTypeRaidz2 VdevSpecType = "raidz2"
	VdevSpecTypeRaidz3 VdevSpecType = "raidz3"
	VdevSpecTypeStripe VdevSpecType = "stripe"
)

// Valid indicates whether the value is a known member of the VdevSpecType enum.
func (e VdevSpecType) Valid() bool {
	switch e {
	case VdevSpecTypeDisk:
		return true
	case VdevSpecTypeMirror:
		return true
	case VdevSpecTypeRaidz1:
		return true
	case VdevSpecTypeRaidz2:
		return true
	case VdevSpecTypeRaidz3:
		return true
	case VdevSpecTypeStripe:
		return true
	default:
		return false
	}
}

// Defines values for ListJobsParamsState.
const (
	Cancelled   ListJobsParamsState = "cancelled"
	Failed      ListJobsParamsState = "failed"
	Interrupted ListJobsParamsState = "interrupted"
	Queued      ListJobsParamsState = "queued"
	Running     ListJobsParamsState = "running"
	Succeeded   ListJobsParamsState = "succeeded"
)

// Valid indicates whether the value is a known member of the ListJobsParamsState enum.
func (e ListJobsParamsState) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Failed:
		return true
	case Interrupted:
		return true
	case Queued:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Bookmark defines model for Bookmark.
type Bookmark struct {
	CreationUnix int64  `json:"creationUnix"`
	Name         string `json:"name"`
}

// BookmarkDestroyRequest defines model for BookmarkDestroyRequest.
type BookmarkDestroyRequest struct {
	// Bookmark Either a short name (combined with the URL dataset) or full `<dataset>#<short>`.
	Bookmark string `json:"bookmark"`
}

// ChangeKeyRequest defines model for ChangeKeyRequest.
type ChangeKeyRequest struct {
	Properties map[string]string `json:"properties"`
}

// Dataset defines model for Dataset.
type Dataset struct {
	AvailableBytes  *int         `json:"availableBytes,omitempty"`
	Compression     *string      `json:"compression,omitempty"`
	Mountpoint      *string      `json:"mountpoint,omitempty"`
	Name            *string      `json:"name,omitempty"`
	RecordSizeBytes *int         `json:"recordSizeBytes,omitempty"`
	ReferencedBytes *int         `json:"referencedBytes,omitempty"`
	Type            *DatasetType `json:"type,omitempty"`
	UsedBytes       *int         `json:"usedBytes,omitempty"`
}

// DatasetType defines model for Dataset.Type.
type DatasetType string

// DatasetBookmarkRequest defines model for DatasetBookmarkRequest.
type DatasetBookmarkRequest struct {
	// Bookmark Full bookmark name `<dataset>#<short>`.
	Bookmark string `json:"bookmark"`
}

// DatasetCloneRequest defines model for DatasetCloneRequest.
type DatasetCloneRequest struct {
	Properties *map[string]string `json:"properties,omitempty"`
	Target     string             `json:"target"`
}

// DatasetCreateSpec defines model for DatasetCreateSpec.
type DatasetCreateSpec struct {
	Name            string                `json:"name"`
	Parent          string                `json:"parent"`
	Properties      *map[string]string    `json:"properties,omitempty"`
	Type            DatasetCreateSpecType `json:"type"`
	VolumeSizeBytes *int                  `json:"volumeSizeBytes,omitempty"`
}

// DatasetCreateSpecType defines model for DatasetCreateSpec.Type.
type DatasetCreateSpecType string

// DatasetDetail defines model for DatasetDetail.
type DatasetDetail struct {
	Dataset    *Dataset           `json:"dataset,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// DatasetDiffEntry defines model for DatasetDiffEntry.
type DatasetDiffEntry struct {
	// Change Change type — added
	Change DatasetDiffEntryChange `json:"change"`

	// NewPath Set only when change is `R` (rename)
	NewPath *string `json:"newPath,omitempty"`
	Path    string  `json:"path"`
}

// DatasetDiffEntryChange Change type — added
type DatasetDiffEntryChange string

// DatasetRenameRequest defines model for DatasetRenameRequest.
type DatasetRenameRequest struct {
	NewName   string `json:"newName"`
	Recursive *bool  `json:"recursive,omitempty"`
}

// Disk defines model for Disk.
type Disk struct {
	InUseByPool *bool   `json:"inUseByPool,omitempty"`
	Model       *string `json:"model,omitempty"`
	Name        *string `json:"name,omitempty"`
	Rotational  *bool   `json:"rotational,omitempty"`
	Serial      *string `json:"serial,omitempty"`
	SizeBytes   *int64  `json:"sizeBytes,omitempty"`
	Wwn         *string `json:"wwn,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Hold defines model for Hold.
type Hold struct {
	CreationUnix int64  `json:"creationUnix"`
	Snapshot     string `json:"snapshot"`
	Tag          string `json:"tag"`
}

// IscsiACL defines model for IscsiACL.
type IscsiACL struct {
	// ChapSecret 12-16 characters per RFC 3720; never returned on reads
	ChapSecret   *string `json:"chapSecret,omitempty"`
	ChapUser     *string `json:"chapUser,omitempty"`
	InitiatorIqn string  `json:"initiatorIqn"`
}

// IscsiLUN defines model for IscsiLUN.
type IscsiLUN struct {
	Backstore string `json:"backstore"`
	Id        int    `json:"id"`

	// Zvol /dev/zvol/<pool>/<name>
	Zvol *string `json:"zvol,omitempty"`
}

// IscsiPortal defines model for IscsiPortal.
type IscsiPortal struct {
	Ip        string                `json:"ip"`
	Port      int                   `json:"port"`
	Transport *IscsiPortalTransport `json:"transport,omitempty"`
}

// IscsiPortalTransport defines model for IscsiPortal.Transport.
type IscsiPortalTransport string

// IscsiTarget defines model for IscsiTarget.
type IscsiTarget struct {
	Iqn string `json:"iqn"`
}

// IscsiTargetDetail defines model for IscsiTargetDetail.
type IscsiTargetDetail struct {
	Acls    *[]IscsiACL    `json:"acls,omitempty"`
	Luns    *[]IscsiLUN    `json:"luns,omitempty"`
	Portals *[]IscsiPortal `json:"portals,omitempty"`
	Target  *IscsiTarget   `json:"target,omitempty"`
}

// Job defines model for Job.
type Job struct {
	Command    *string             `json:"command,omitempty"`
	CreatedAt  *time.Time          `json:"createdAt,omitempty"`
	Error      *string             `json:"error,omitempty"`
	ExitCode   *int                `json:"exitCode,omitempty"`
	FinishedAt *time.Time          `json:"finishedAt,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Kind       *string             `json:"kind,omitempty"`
	StartedAt  *time.Time          `json:"startedAt,omitempty"`
	State      *string             `json:"state,omitempty"`
	Stderr     *string             `json:"stderr,omitempty"`
	Stdout     *string             `json:"stdout,omitempty"`
	Target     *string             `json:"target,omitempty"`
}

// Krb5Config defines model for Krb5Config.
type Krb5Config struct {
	// DefaultRealm Uppercase realm name (e.g. EXAMPLE.COM)
	DefaultRealm   string               `json:"defaultRealm"`
	DnsLookupKdc   *bool                `json:"dnsLookupKdc,omitempty"`
	DnsLookupRealm *bool                `json:"dnsLookupRealm,omitempty"`
	DomainRealm    *map[string]string   `json:"domainRealm,omitempty"`
	Realms         map[string]Krb5Realm `json:"realms"`
}

// Krb5IdmapdConfig defines model for Krb5IdmapdConfig.
type Krb5IdmapdConfig struct {
	// Domain NFSv4 ID-map domain (typically lowercase realm)
	Domain    string `json:"domain"`
	Verbosity *int   `json:"verbosity,omitempty"`
}

// Krb5KeytabEntry defines model for Krb5KeytabEntry.
type Krb5KeytabEntry struct {
	Encryption string `json:"encryption"`
	Kvno       int    `json:"kvno"`
	Principal  string `json:"principal"`
}

// Krb5KeytabUpload defines model for Krb5KeytabUpload.
type Krb5KeytabUpload struct {
	// Data Base64-encoded raw keytab bytes (must begin with magic byte 0x05)
	Data []byte `json:"data"`
}

// Krb5Realm defines model for Krb5Realm.
type Krb5Realm struct {
	AdminServer   *string  `json:"adminServer,omitempty"`
	DefaultDomain *string  `json:"defaultDomain,omitempty"`
	Kdc           []string `json:"kdc"`
}

// LoadKeyRequest defines model for LoadKeyRequest.
type LoadKeyRequest struct {
	Keylocation *string `json:"keylocation,omitempty"`
	Recursive   *bool   `json:"recursive,omitempty"`
}

// MetadataPatch defines model for MetadataPatch.
type MetadataPatch struct {
	Description *string            `json:"description,omitempty"`
	DisplayName *string            `json:"display_name,omitempty"`
	Tags        *map[string]string `json:"tags,omitempty"`
}

// NfsActiveExport defines model for NfsActiveExport.
type NfsActiveExport struct {
	Client  string `json:"Client"`
	Options string `json:"Options"`
	Path    string `json:"Path"`
}

// NfsClientRule defines model for NfsClientRule.
type NfsClientRule struct {
	// Options Comma-separated NFS export options (e.g. "rw,sync,sec=krb5p")
	Options string `json:"options"`

	// Spec CIDR, IP, "*", or hostname/wildcard pattern
	Spec string `json:"spec"`
}

// NfsExport defines model for NfsExport.
type NfsExport struct {
	Clients []NfsClientRule `json:"clients"`

	// Name Filename-safe identifier (alnum, -, _; 1-64 chars)
	Name string `json:"name"`

	// Path Absolute host path
	Path string `json:"path"`
}

// NvmeofDHChapConfig Per-host DH-HMAC-CHAP (NVMe TP4022) configuration. Secrets must be in "DHHC-1:NN:..." form. Empty fields are left unchanged on PATCH-style updates.
type NvmeofDHChapConfig struct {
	// CtrlKey Controller secret for bidirectional auth
	CtrlKey *string                    `json:"ctrlKey,omitempty"`
	Dhgroup *NvmeofDHChapConfigDhgroup `json:"dhgroup,omitempty"`
	Hash    *NvmeofDHChapConfigHash    `json:"hash,omitempty"`

	// Key Host secret in TP4022 format
	Key *string `json:"key,omitempty"`
}

// NvmeofDHChapConfigDhgroup defines model for NvmeofDHChapConfig.Dhgroup.
type NvmeofDHChapConfigDhgroup string

// NvmeofDHChapConfigHash defines model for NvmeofDHChapConfig.Hash.
type NvmeofDHChapConfigHash string

// NvmeofDHChapDetail Read-side DH-HMAC-CHAP detail. Raw key material is never returned.
type NvmeofDHChapDetail struct {
	Dhgroup    *string `json:"dhgroup,omitempty"`
	HasCtrlKey bool    `json:"hasCtrlKey"`
	HasKey     bool    `json:"hasKey"`
	Hash       *string `json:"hash,omitempty"`
}

// NvmeofHost defines model for NvmeofHost.
type NvmeofHost struct {
	HostNqn string `json:"hostNqn"`
}

// NvmeofNamespace defines model for NvmeofNamespace.
type NvmeofNamespace struct {
	// DevicePath Must start with /dev/
	DevicePath string `json:"devicePath"`
	Enabled    *bool  `json:"enabled,omitempty"`
	Nsid       int    `json:"nsid"`
}

// NvmeofPort defines model for NvmeofPort.
type NvmeofPort struct {
	Id        int                 `json:"id"`
	Ip        string              `json:"ip"`
	Port      int                 `json:"port"`
	Transport NvmeofPortTransport `json:"transport"`
}

// NvmeofPortTransport defines model for NvmeofPort.Transport.
type NvmeofPortTransport string

// NvmeofSubsystem defines model for NvmeofSubsystem.
type NvmeofSubsystem struct {
	AllowAnyHost *bool   `json:"allowAnyHost,omitempty"`
	Nqn          string  `json:"nqn"`
	Serial       *string `json:"serial,omitempty"`
}

// NvmeofSubsystemDetail defines model for NvmeofSubsystemDetail.
type NvmeofSubsystemDetail struct {
	AllowedHosts *[]string          `json:"allowedHosts,omitempty"`
	Namespaces   *[]NvmeofNamespace `json:"namespaces,omitempty"`
	Subsystem    *NvmeofSubsystem   `json:"subsystem,omitempty"`
}

// Pool defines model for Pool.
type Pool struct {
	Allocated        *int    `json:"allocated,omitempty"`
	CapacityPct      *int    `json:"capacityPct,omitempty"`
	DedupRatio       *string `json:"dedupRatio,omitempty"`
	FragmentationPct *int    `json:"fragmentationPct,omitempty"`
	Free             *int    `json:"free,omitempty"`
	Health           *string `json:"health,omitempty"`
	Name             *string `json:"name,omitempty"`
	ReadOnly         *bool   `json:"readOnly,omitempty"`
	SizeBytes        *int    `json:"sizeBytes,omitempty"`
}

// PoolCreateSpec defines model for PoolCreateSpec.
type PoolCreateSpec struct {
	Cache *[]string   `json:"cache,omitempty"`
	Log   *[]VdevSpec `json:"log,omitempty"`
	Name  string      `json:"name"`
	Spare *[]string   `json:"spare,omitempty"`
	Vdevs []VdevSpec  `json:"vdevs"`
}

// PoolDetail defines model for PoolDetail.
type PoolDetail struct {
	Pool       *Pool              `json:"pool,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
	Status     *struct {
		State *string `json:"state,omitempty"`
		Vdevs *[]Vdev `json:"vdevs,omitempty"`
	} `json:"status,omitempty"`
}

// PoolPropertiesPatch defines model for PoolPropertiesPatch.
type PoolPropertiesPatch struct {
	Properties map[string]string `json:"properties"`
}

// PoolSyncRequest defines model for PoolSyncRequest.
type PoolSyncRequest struct {
	// Names Pool names to sync; empty/omitted means all pools.
	Names *[]string `json:"names,omitempty"`
}

// PoolTrimRequest defines model for PoolTrimRequest.
type PoolTrimRequest struct {
	// Disk Optional vdev path; absent trims the whole pool
	Disk *string `json:"disk,omitempty"`
}

// RdmaAdapter defines model for RdmaAdapter.
type RdmaAdapter struct {
	BoardId *string `json:"boardId,omitempty"`
	HcaType *string `json:"hcaType,omitempty"`

	// Name e.g. mlx5_0
	Name  string             `json:"name"`
	Ports *[]RdmaAdapterPort `json:"ports,omitempty"`
}

// RdmaAdapterPort defines model for RdmaAdapterPort.
type RdmaAdapterPort struct {
	Gids *[]string `json:"gids,omitempty"`

	// LinkLayer InfiniBand or Ethernet (RoCE)
	LinkLayer string `json:"linkLayer"`
	Number    int    `json:"number"`

	// State ACTIVE, DOWN, INIT, ARMED
	State string `json:"state"`
}

// ResourceMetadata defines model for ResourceMetadata.
type ResourceMetadata struct {
	Description *string            `json:"description,omitempty"`
	DisplayName *string            `json:"displayName,omitempty"`
	Id          *int               `json:"id,omitempty"`
	Kind        *string            `json:"kind,omitempty"`
	Tags        *map[string]string `json:"tags,omitempty"`
	ZfsName     *string            `json:"zfsName,omitempty"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	CreationUnix    *int    `json:"creationUnix,omitempty"`
	Dataset         *string `json:"dataset,omitempty"`
	Name            *string `json:"name,omitempty"`
	ReferencedBytes *int    `json:"referencedBytes,omitempty"`
	ShortName       *string `json:"shortName,omitempty"`
	UsedBytes       *int    `json:"usedBytes,omitempty"`
}

// SnapshotHoldRequest defines model for SnapshotHoldRequest.
type SnapshotHoldRequest struct {
	Recursive *bool  `json:"recursive,omitempty"`
	Tag       string `json:"tag"`
}

// SnapshotReleaseRequest defines model for SnapshotReleaseRequest.
type SnapshotReleaseRequest struct {
	Recursive *bool  `json:"recursive,omitempty"`
	Tag       string `json:"tag"`
}

// Vdev defines model for Vdev.
type Vdev struct {
	ChecksumErrors *int    `json:"checksumErrors,omitempty"`
	Children       *[]Vdev `json:"children,omitempty"`
	Path           *string `json:"path,omitempty"`
	ReadErrors     *int    `json:"readErrors,omitempty"`
	State          *string `json:"state,omitempty"`
	Type           *string `json:"type,omitempty"`
	WriteErrors    *int    `json:"writeErrors,omitempty"`
}

// VdevSpec defines model for VdevSpec.
type VdevSpec struct {
	Disks []string     `json:"disks"`
	Type  VdevSpecType `json:"type"`
}

// VdevSpecType defines model for VdevSpec.Type.
type VdevSpecType string

// Accepted defines model for Accepted.
type Accepted struct {
	JobId *openapi_types.UUID `json:"jobId,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListDatasetsParams defines parameters for ListDatasets.
type ListDatasetsParams struct {
	Pool *string `form:"pool,omitempty" json:"pool,omitempty"`
}

// DestroyDatasetParams defines parameters for DestroyDataset.
type DestroyDatasetParams struct {
	Recursive *bool `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// PatchDatasetPropsJSONBody defines parameters for PatchDatasetProps.
type PatchDatasetPropsJSONBody struct {
	Properties map[string]string `json:"properties"`
}

// DiffDatasetParams defines parameters for DiffDataset.
type DiffDatasetParams struct {
	To *string `form:"to,omitempty" json:"to,omitempty"`
}

// ReceiveDatasetParams defines parameters for ReceiveDataset.
type ReceiveDatasetParams struct {
	Force     *bool   `form:"force,omitempty" json:"force,omitempty"`
	Resumable *bool   `form:"resumable,omitempty" json:"resumable,omitempty"`
	Origin    *string `form:"origin,omitempty" json:"origin,omitempty"`
}

// RollbackDatasetJSONBody defines parameters for RollbackDataset.
type RollbackDatasetJSONBody struct {
	Snapshot string `json:"snapshot"`
}

// SendDatasetParams defines parameters for SendDataset.
type SendDatasetParams struct {
	Recursive    *bool   `form:"recursive,omitempty" json:"recursive,omitempty"`
	Raw          *bool   `form:"raw,omitempty" json:"raw,omitempty"`
	Compressed   *bool   `form:"compressed,omitempty" json:"compressed,omitempty"`
	LargeBlock   *bool   `form:"largeBlock,omitempty" json:"largeBlock,omitempty"`
	EmbeddedData *bool   `form:"embeddedData,omitempty" json:"embeddedData,omitempty"`
	From         *string `form:"from,omitempty" json:"from,omitempty"`
}

// UnloadDatasetKeyJSONBody defines parameters for UnloadDatasetKey.
type UnloadDatasetKeyJSONBody struct {
	Recursive *bool `json:"recursive,omitempty"`
}

// CreateIscsiTargetJSONBody defines parameters for CreateIscsiTarget.
type CreateIscsiTargetJSONBody struct {
	Iqn string `json:"iqn"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	State  *ListJobsParamsState `form:"state,omitempty" json:"state,omitempty"`
	Limit  *int                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListJobsParamsState defines parameters for ListJobs.
type ListJobsParamsState string

// LinkNvmeofSubsystemJSONBody defines parameters for LinkNvmeofSubsystem.
type LinkNvmeofSubsystemJSONBody struct {
	Nqn string `json:"nqn"`
}

// ScrubPoolParams defines parameters for ScrubPool.
type ScrubPoolParams struct {
	Action *string `form:"action,omitempty" json:"action,omitempty"`
}

// TrimPoolParams defines parameters for TrimPool.
type TrimPoolParams struct {
	Action *string `form:"action,omitempty" json:"action,omitempty"`
}

// UpgradePoolParams defines parameters for UpgradePool.
type UpgradePoolParams struct {
	// All When true, upgrade all pools (`zpool upgrade -a`); the path name is ignored.
	All *bool `form:"all,omitempty" json:"all,omitempty"`
}

// WaitPoolParams defines parameters for WaitPool.
type WaitPoolParams struct {
	Activity   string `form:"activity" json:"activity"`
	TimeoutSec *int   `form:"timeoutSec,omitempty" json:"timeoutSec,omitempty"`
}

// ListSnapshotsParams defines parameters for ListSnapshots.
type ListSnapshotsParams struct {
	Dataset *string `form:"dataset,omitempty" json:"dataset,omitempty"`
}

// CreateSnapshotJSONBody defines parameters for CreateSnapshot.
type CreateSnapshotJSONBody struct {
	Dataset   string `json:"dataset"`
	Name      string `json:"name"`
	Recursive *bool  `json:"recursive,omitempty"`
}

// CreateDatasetJSONRequestBody defines body for CreateDataset for application/json ContentType.
type CreateDatasetJSONRequestBody = DatasetCreateSpec

// PatchDatasetPropsJSONRequestBody defines body for PatchDatasetProps for application/json ContentType.
type PatchDatasetPropsJSONRequestBody PatchDatasetPropsJSONBody

// BookmarkSnapshotJSONRequestBody defines body for BookmarkSnapshot for application/json ContentType.
type BookmarkSnapshotJSONRequestBody = DatasetBookmarkRequest

// ChangeDatasetKeyJSONRequestBody defines body for ChangeDatasetKey for application/json ContentType.
type ChangeDatasetKeyJSONRequestBody = ChangeKeyRequest

// CloneDatasetJSONRequestBody defines body for CloneDataset for application/json ContentType.
type CloneDatasetJSONRequestBody = DatasetCloneRequest

// DestroyDatasetBookmarkJSONRequestBody defines body for DestroyDatasetBookmark for application/json ContentType.
type DestroyDatasetBookmarkJSONRequestBody = BookmarkDestroyRequest

// LoadDatasetKeyJSONRequestBody defines body for LoadDatasetKey for application/json ContentType.
type LoadDatasetKeyJSONRequestBody = LoadKeyRequest

// PatchDatasetMetadataJSONRequestBody defines body for PatchDatasetMetadata for application/json ContentType.
type PatchDatasetMetadataJSONRequestBody = MetadataPatch

// RenameDatasetJSONRequestBody defines body for RenameDataset for application/json ContentType.
type RenameDatasetJSONRequestBody = DatasetRenameRequest

// RollbackDatasetJSONRequestBody defines body for RollbackDataset for application/json ContentType.
type RollbackDatasetJSONRequestBody RollbackDatasetJSONBody

// UnloadDatasetKeyJSONRequestBody defines body for UnloadDatasetKey for application/json ContentType.
type UnloadDatasetKeyJSONRequestBody UnloadDatasetKeyJSONBody

// CreateIscsiTargetJSONRequestBody defines body for CreateIscsiTarget for application/json ContentType.
type CreateIscsiTargetJSONRequestBody CreateIscsiTargetJSONBody

// CreateIscsiACLJSONRequestBody defines body for CreateIscsiACL for application/json ContentType.
type CreateIscsiACLJSONRequestBody = IscsiACL

// CreateIscsiLUNJSONRequestBody defines body for CreateIscsiLUN for application/json ContentType.
type CreateIscsiLUNJSONRequestBody = IscsiLUN

// CreateIscsiPortalJSONRequestBody defines body for CreateIscsiPortal for application/json ContentType.
type CreateIscsiPortalJSONRequestBody = IscsiPortal

// SetKrb5ConfigJSONRequestBody defines body for SetKrb5Config for application/json ContentType.
type SetKrb5ConfigJSONRequestBody = Krb5Config

// SetKrb5IdmapdJSONRequestBody defines body for SetKrb5Idmapd for application/json ContentType.
type SetKrb5IdmapdJSONRequestBody = Krb5IdmapdConfig

// UploadKrb5KeytabJSONRequestBody defines body for UploadKrb5Keytab for application/json ContentType.
type UploadKrb5KeytabJSONRequestBody = Krb5KeytabUpload

// CreateNfsExportJSONRequestBody defines body for CreateNfsExport for application/json ContentType.
type CreateNfsExportJSONRequestBody = NfsExport

// UpdateNfsExportJSONRequestBody defines body for UpdateNfsExport for application/json ContentType.
type UpdateNfsExportJSONRequestBody = NfsExport

// SetNvmeofHostDHChapJSONRequestBody defines body for SetNvmeofHostDHChap for application/json ContentType.
type SetNvmeofHostDHChapJSONRequestBody = NvmeofDHChapConfig

// CreateNvmeofPortJSONRequestBody defines body for CreateNvmeofPort for application/json ContentType.
type CreateNvmeofPortJSONRequestBody = NvmeofPort

// LinkNvmeofSubsystemJSONRequestBody defines body for LinkNvmeofSubsystem for application/json ContentType.
type LinkNvmeofSubsystemJSONRequestBody LinkNvmeofSubsystemJSONBody

// CreateNvmeofSubsystemJSONRequestBody defines body for CreateNvmeofSubsystem for application/json ContentType.
type CreateNvmeofSubsystemJSONRequestBody = NvmeofSubsystem

// AllowNvmeofHostJSONRequestBody defines body for AllowNvmeofHost for application/json ContentType.
type AllowNvmeofHostJSONRequestBody = NvmeofHost

// AddNvmeofNamespaceJSONRequestBody defines body for AddNvmeofNamespace for application/json ContentType.
type AddNvmeofNamespaceJSONRequestBody = NvmeofNamespace

// CreatePoolJSONRequestBody defines body for CreatePool for application/json ContentType.
type CreatePoolJSONRequestBody = PoolCreateSpec

// SyncPoolsJSONRequestBody defines body for SyncPools for application/json ContentType.
type SyncPoolsJSONRequestBody = PoolSyncRequest

// PatchPoolMetadataJSONRequestBody defines body for PatchPoolMetadata for application/json ContentType.
type PatchPoolMetadataJSONRequestBody = MetadataPatch

// PatchPoolPropertiesJSONRequestBody defines body for PatchPoolProperties for application/json ContentType.
type PatchPoolPropertiesJSONRequestBody = PoolPropertiesPatch

// TrimPoolJSONRequestBody defines body for TrimPool for application/json ContentType.
type TrimPoolJSONRequestBody = PoolTrimRequest

// CreateSnapshotJSONRequestBody defines body for CreateSnapshot for application/json ContentType.
type CreateSnapshotJSONRequestBody CreateSnapshotJSONBody

// HoldSnapshotJSONRequestBody defines body for HoldSnapshot for application/json ContentType.
type HoldSnapshotJSONRequestBody = SnapshotHoldRequest

// PatchSnapshotMetadataJSONRequestBody defines body for PatchSnapshotMetadata for application/json ContentType.
type PatchSnapshotMetadataJSONRequestBody = MetadataPatch

// ReleaseSnapshotJSONRequestBody defines body for ReleaseSnapshot for application/json ContentType.
type ReleaseSnapshotJSONRequestBody = SnapshotReleaseRequest
