// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DatasetType.
const (
	DatasetTypeFilesystem DatasetType = "filesystem"
	DatasetTypeVolume     DatasetType = "volume"
)

// Valid indicates whether the value is a known member of the DatasetType enum.
func (e DatasetType) Valid() bool {
	switch e {
	case DatasetTypeFilesystem:
		return true
	case DatasetTypeVolume:
		return true
	default:
		return false
	}
}

// Defines values for DatasetCreateSpecType.
const (
	DatasetCreateSpecTypeFilesystem DatasetCreateSpecType = "filesystem"
	DatasetCreateSpecTypeVolume     DatasetCreateSpecType = "volume"
)

// Valid indicates whether the value is a known member of the DatasetCreateSpecType enum.
func (e DatasetCreateSpecType) Valid() bool {
	switch e {
	case DatasetCreateSpecTypeFilesystem:
		return true
	case DatasetCreateSpecTypeVolume:
		return true
	default:
		return false
	}
}

// Defines values for VdevSpecType.
const (
	VdevSpecTypeDisk   VdevSpecType = "disk"
	VdevSpecTypeMirror VdevSpecType = "mirror"
	VdevSpecTypeRaidz1 VdevSpecType = "raidz1"
	VdevSpecTypeRaidz2 VdevSpecType = "raidz2"
	VdevSpecTypeRaidz3 VdevSpecType = "raidz3"
	VdevSpecTypeStripe VdevSpecType = "stripe"
)

// Valid indicates whether the value is a known member of the VdevSpecType enum.
func (e VdevSpecType) Valid() bool {
	switch e {
	case VdevSpecTypeDisk:
		return true
	case VdevSpecTypeMirror:
		return true
	case VdevSpecTypeRaidz1:
		return true
	case VdevSpecTypeRaidz2:
		return true
	case VdevSpecTypeRaidz3:
		return true
	case VdevSpecTypeStripe:
		return true
	default:
		return false
	}
}

// Defines values for ListJobsParamsState.
const (
	Cancelled   ListJobsParamsState = "cancelled"
	Failed      ListJobsParamsState = "failed"
	Interrupted ListJobsParamsState = "interrupted"
	Queued      ListJobsParamsState = "queued"
	Running     ListJobsParamsState = "running"
	Succeeded   ListJobsParamsState = "succeeded"
)

// Valid indicates whether the value is a known member of the ListJobsParamsState enum.
func (e ListJobsParamsState) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Failed:
		return true
	case Interrupted:
		return true
	case Queued:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// ChangeKeyRequest defines model for ChangeKeyRequest.
type ChangeKeyRequest struct {
	Properties map[string]string `json:"properties"`
}

// Dataset defines model for Dataset.
type Dataset struct {
	AvailableBytes  *int         `json:"availableBytes,omitempty"`
	Compression     *string      `json:"compression,omitempty"`
	Mountpoint      *string      `json:"mountpoint,omitempty"`
	Name            *string      `json:"name,omitempty"`
	RecordSizeBytes *int         `json:"recordSizeBytes,omitempty"`
	ReferencedBytes *int         `json:"referencedBytes,omitempty"`
	Type            *DatasetType `json:"type,omitempty"`
	UsedBytes       *int         `json:"usedBytes,omitempty"`
}

// DatasetType defines model for Dataset.Type.
type DatasetType string

// DatasetCloneRequest defines model for DatasetCloneRequest.
type DatasetCloneRequest struct {
	Properties *map[string]string `json:"properties,omitempty"`
	Target     string             `json:"target"`
}

// DatasetCreateSpec defines model for DatasetCreateSpec.
type DatasetCreateSpec struct {
	Name            string                `json:"name"`
	Parent          string                `json:"parent"`
	Properties      *map[string]string    `json:"properties,omitempty"`
	Type            DatasetCreateSpecType `json:"type"`
	VolumeSizeBytes *int                  `json:"volumeSizeBytes,omitempty"`
}

// DatasetCreateSpecType defines model for DatasetCreateSpec.Type.
type DatasetCreateSpecType string

// DatasetDetail defines model for DatasetDetail.
type DatasetDetail struct {
	Dataset    *Dataset           `json:"dataset,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// DatasetRenameRequest defines model for DatasetRenameRequest.
type DatasetRenameRequest struct {
	NewName   string `json:"newName"`
	Recursive *bool  `json:"recursive,omitempty"`
}

// Disk defines model for Disk.
type Disk struct {
	InUseByPool *bool   `json:"inUseByPool,omitempty"`
	Model       *string `json:"model,omitempty"`
	Name        *string `json:"name,omitempty"`
	Rotational  *bool   `json:"rotational,omitempty"`
	Serial      *string `json:"serial,omitempty"`
	SizeBytes   *int64  `json:"sizeBytes,omitempty"`
	Wwn         *string `json:"wwn,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Job defines model for Job.
type Job struct {
	Command    *string             `json:"command,omitempty"`
	CreatedAt  *time.Time          `json:"createdAt,omitempty"`
	Error      *string             `json:"error,omitempty"`
	ExitCode   *int                `json:"exitCode,omitempty"`
	FinishedAt *time.Time          `json:"finishedAt,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Kind       *string             `json:"kind,omitempty"`
	StartedAt  *time.Time          `json:"startedAt,omitempty"`
	State      *string             `json:"state,omitempty"`
	Stderr     *string             `json:"stderr,omitempty"`
	Stdout     *string             `json:"stdout,omitempty"`
	Target     *string             `json:"target,omitempty"`
}

// LoadKeyRequest defines model for LoadKeyRequest.
type LoadKeyRequest struct {
	Keylocation *string `json:"keylocation,omitempty"`
	Recursive   *bool   `json:"recursive,omitempty"`
}

// MetadataPatch defines model for MetadataPatch.
type MetadataPatch struct {
	Description *string            `json:"description,omitempty"`
	DisplayName *string            `json:"display_name,omitempty"`
	Tags        *map[string]string `json:"tags,omitempty"`
}

// Pool defines model for Pool.
type Pool struct {
	Allocated        *int    `json:"allocated,omitempty"`
	CapacityPct      *int    `json:"capacityPct,omitempty"`
	DedupRatio       *string `json:"dedupRatio,omitempty"`
	FragmentationPct *int    `json:"fragmentationPct,omitempty"`
	Free             *int    `json:"free,omitempty"`
	Health           *string `json:"health,omitempty"`
	Name             *string `json:"name,omitempty"`
	ReadOnly         *bool   `json:"readOnly,omitempty"`
	SizeBytes        *int    `json:"sizeBytes,omitempty"`
}

// PoolCreateSpec defines model for PoolCreateSpec.
type PoolCreateSpec struct {
	Cache *[]string   `json:"cache,omitempty"`
	Log   *[]VdevSpec `json:"log,omitempty"`
	Name  string      `json:"name"`
	Spare *[]string   `json:"spare,omitempty"`
	Vdevs []VdevSpec  `json:"vdevs"`
}

// PoolDetail defines model for PoolDetail.
type PoolDetail struct {
	Pool       *Pool              `json:"pool,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
	Status     *struct {
		State *string `json:"state,omitempty"`
		Vdevs *[]Vdev `json:"vdevs,omitempty"`
	} `json:"status,omitempty"`
}

// PoolPropertiesPatch defines model for PoolPropertiesPatch.
type PoolPropertiesPatch struct {
	Properties map[string]string `json:"properties"`
}

// PoolTrimRequest defines model for PoolTrimRequest.
type PoolTrimRequest struct {
	// Disk Optional vdev path; absent trims the whole pool
	Disk *string `json:"disk,omitempty"`
}

// ResourceMetadata defines model for ResourceMetadata.
type ResourceMetadata struct {
	Description *string            `json:"description,omitempty"`
	DisplayName *string            `json:"displayName,omitempty"`
	Id          *int               `json:"id,omitempty"`
	Kind        *string            `json:"kind,omitempty"`
	Tags        *map[string]string `json:"tags,omitempty"`
	ZfsName     *string            `json:"zfsName,omitempty"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	CreationUnix    *int    `json:"creationUnix,omitempty"`
	Dataset         *string `json:"dataset,omitempty"`
	Name            *string `json:"name,omitempty"`
	ReferencedBytes *int    `json:"referencedBytes,omitempty"`
	ShortName       *string `json:"shortName,omitempty"`
	UsedBytes       *int    `json:"usedBytes,omitempty"`
}

// Vdev defines model for Vdev.
type Vdev struct {
	ChecksumErrors *int    `json:"checksumErrors,omitempty"`
	Children       *[]Vdev `json:"children,omitempty"`
	Path           *string `json:"path,omitempty"`
	ReadErrors     *int    `json:"readErrors,omitempty"`
	State          *string `json:"state,omitempty"`
	Type           *string `json:"type,omitempty"`
	WriteErrors    *int    `json:"writeErrors,omitempty"`
}

// VdevSpec defines model for VdevSpec.
type VdevSpec struct {
	Disks []string     `json:"disks"`
	Type  VdevSpecType `json:"type"`
}

// VdevSpecType defines model for VdevSpec.Type.
type VdevSpecType string

// Accepted defines model for Accepted.
type Accepted struct {
	JobId *openapi_types.UUID `json:"jobId,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListDatasetsParams defines parameters for ListDatasets.
type ListDatasetsParams struct {
	Pool *string `form:"pool,omitempty" json:"pool,omitempty"`
}

// DestroyDatasetParams defines parameters for DestroyDataset.
type DestroyDatasetParams struct {
	Recursive *bool `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// PatchDatasetPropsJSONBody defines parameters for PatchDatasetProps.
type PatchDatasetPropsJSONBody struct {
	Properties map[string]string `json:"properties"`
}

// ReceiveDatasetParams defines parameters for ReceiveDataset.
type ReceiveDatasetParams struct {
	Force     *bool   `form:"force,omitempty" json:"force,omitempty"`
	Resumable *bool   `form:"resumable,omitempty" json:"resumable,omitempty"`
	Origin    *string `form:"origin,omitempty" json:"origin,omitempty"`
}

// RollbackDatasetJSONBody defines parameters for RollbackDataset.
type RollbackDatasetJSONBody struct {
	Snapshot string `json:"snapshot"`
}

// SendDatasetParams defines parameters for SendDataset.
type SendDatasetParams struct {
	Recursive    *bool   `form:"recursive,omitempty" json:"recursive,omitempty"`
	Raw          *bool   `form:"raw,omitempty" json:"raw,omitempty"`
	Compressed   *bool   `form:"compressed,omitempty" json:"compressed,omitempty"`
	LargeBlock   *bool   `form:"largeBlock,omitempty" json:"largeBlock,omitempty"`
	EmbeddedData *bool   `form:"embeddedData,omitempty" json:"embeddedData,omitempty"`
	From         *string `form:"from,omitempty" json:"from,omitempty"`
}

// UnloadDatasetKeyJSONBody defines parameters for UnloadDatasetKey.
type UnloadDatasetKeyJSONBody struct {
	Recursive *bool `json:"recursive,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	State  *ListJobsParamsState `form:"state,omitempty" json:"state,omitempty"`
	Limit  *int                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListJobsParamsState defines parameters for ListJobs.
type ListJobsParamsState string

// ScrubPoolParams defines parameters for ScrubPool.
type ScrubPoolParams struct {
	Action *string `form:"action,omitempty" json:"action,omitempty"`
}

// TrimPoolParams defines parameters for TrimPool.
type TrimPoolParams struct {
	Action *string `form:"action,omitempty" json:"action,omitempty"`
}

// WaitPoolParams defines parameters for WaitPool.
type WaitPoolParams struct {
	Activity   string `form:"activity" json:"activity"`
	TimeoutSec *int   `form:"timeoutSec,omitempty" json:"timeoutSec,omitempty"`
}

// ListSnapshotsParams defines parameters for ListSnapshots.
type ListSnapshotsParams struct {
	Dataset *string `form:"dataset,omitempty" json:"dataset,omitempty"`
}

// CreateSnapshotJSONBody defines parameters for CreateSnapshot.
type CreateSnapshotJSONBody struct {
	Dataset   string `json:"dataset"`
	Name      string `json:"name"`
	Recursive *bool  `json:"recursive,omitempty"`
}

// CreateDatasetJSONRequestBody defines body for CreateDataset for application/json ContentType.
type CreateDatasetJSONRequestBody = DatasetCreateSpec

// PatchDatasetPropsJSONRequestBody defines body for PatchDatasetProps for application/json ContentType.
type PatchDatasetPropsJSONRequestBody PatchDatasetPropsJSONBody

// ChangeDatasetKeyJSONRequestBody defines body for ChangeDatasetKey for application/json ContentType.
type ChangeDatasetKeyJSONRequestBody = ChangeKeyRequest

// CloneDatasetJSONRequestBody defines body for CloneDataset for application/json ContentType.
type CloneDatasetJSONRequestBody = DatasetCloneRequest

// LoadDatasetKeyJSONRequestBody defines body for LoadDatasetKey for application/json ContentType.
type LoadDatasetKeyJSONRequestBody = LoadKeyRequest

// PatchDatasetMetadataJSONRequestBody defines body for PatchDatasetMetadata for application/json ContentType.
type PatchDatasetMetadataJSONRequestBody = MetadataPatch

// RenameDatasetJSONRequestBody defines body for RenameDataset for application/json ContentType.
type RenameDatasetJSONRequestBody = DatasetRenameRequest

// RollbackDatasetJSONRequestBody defines body for RollbackDataset for application/json ContentType.
type RollbackDatasetJSONRequestBody RollbackDatasetJSONBody

// UnloadDatasetKeyJSONRequestBody defines body for UnloadDatasetKey for application/json ContentType.
type UnloadDatasetKeyJSONRequestBody UnloadDatasetKeyJSONBody

// CreatePoolJSONRequestBody defines body for CreatePool for application/json ContentType.
type CreatePoolJSONRequestBody = PoolCreateSpec

// PatchPoolMetadataJSONRequestBody defines body for PatchPoolMetadata for application/json ContentType.
type PatchPoolMetadataJSONRequestBody = MetadataPatch

// PatchPoolPropertiesJSONRequestBody defines body for PatchPoolProperties for application/json ContentType.
type PatchPoolPropertiesJSONRequestBody = PoolPropertiesPatch

// TrimPoolJSONRequestBody defines body for TrimPool for application/json ContentType.
type TrimPoolJSONRequestBody = PoolTrimRequest

// CreateSnapshotJSONRequestBody defines body for CreateSnapshot for application/json ContentType.
type CreateSnapshotJSONRequestBody CreateSnapshotJSONBody

// PatchSnapshotMetadataJSONRequestBody defines body for PatchSnapshotMetadata for application/json ContentType.
type PatchSnapshotMetadataJSONRequestBody = MetadataPatch
