apiVersion: v2
name: prometheus
description: Prometheus — Monitoring system and time-series database.
type: application
version: 0.1.0
appVersion: "v2.54.1"
icon: file://../icon.svg
home: https://prometheus.io
sources:
  - https://prometheus.io
maintainers:
  - name: NovaNas
    url: https://github.com/azrtydxb/novanas
keywords:
  - observability
  - prometheus
