#!/bin/bash
set -euo pipefail

# Keycloak bootstrap script, runs as ExecStartPre.
# Fetches DB password from OpenBao and writes environment for Keycloak startup.
#
# Keycloak will read these environment variables to connect to PostgreSQL.

BAO_ADDR="${BAO_ADDR:-https://localhost:8200}"
BAO_TOKEN_FILE="${BAO_TOKEN_FILE:-/etc/keycloak/bao-token}"
DB_NAME="${DB_NAME:-keycloak}"
DB_USER="${DB_USER:-keycloak}"
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"
RUNTIME_ENV="/run/keycloak/keycloak.env"

# Ensure runtime directory exists
mkdir -p /run/keycloak
chown keycloak:keycloak /run/keycloak
chmod 0755 /run/keycloak

if [[ ! -f "$BAO_TOKEN_FILE" ]]; then
    echo "Error: OpenBao token not found at $BAO_TOKEN_FILE" >&2
    echo "Did setup-openbao.sh complete successfully?" >&2
    exit 1
fi

BAO_TOKEN=$(cat "$BAO_TOKEN_FILE")

# Fetch Keycloak DB password from OpenBao
echo "Fetching Keycloak DB password from OpenBao..."
DB_PASSWORD=$(curl -sk \
    -H "X-Vault-Token: $BAO_TOKEN" \
    "$BAO_ADDR/v1/secret/data/keycloak/db" \
    | jq -r '.data.data.password' 2>/dev/null) || {
    echo "Error: failed to fetch password from OpenBao" >&2
    exit 1
}

if [[ -z "$DB_PASSWORD" || "$DB_PASSWORD" == "null" ]]; then
    echo "Error: Keycloak DB password not found in OpenBao" >&2
    exit 1
fi

# Generate Keycloak configuration
# These are read by kc.sh via KEYCLOAK_* environment variables
cat > "$RUNTIME_ENV" << EOF
# Generated by nova-keycloak-bootstrap at $(date -u +%Y-%m-%dT%H:%M:%SZ)
KC_DB=postgres
KC_DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
KC_DB_USERNAME=${DB_USER}
KC_DB_PASSWORD=${DB_PASSWORD}
KC_HOSTNAME=localhost
KC_HOSTNAME_STRICT=false
KC_HOSTNAME_STRICT_HTTPS=false
KC_HTTP_ENABLED=false
KC_PROXY_HEADERS=forwarded
KC_LOG_LEVEL=INFO
KEYCLOAK_ADMIN=admin
# KEYCLOAK_ADMIN_PASSWORD will be set by realm import if needed
EOF

chmod 0600 "$RUNTIME_ENV"
chown keycloak:keycloak "$RUNTIME_ENV"

echo "Keycloak environment written to $RUNTIME_ENV"

# Check database connectivity
echo "Verifying PostgreSQL connectivity..."
PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1" > /dev/null || {
    echo "Warning: could not connect to PostgreSQL (may not be ready yet)" >&2
    # Don't fail here; Keycloak will retry
}

echo "Keycloak bootstrap completed"
