package network

import (
	"fmt"
	"net"
	"strings"
)

// StaticConfig is a static IP configuration for one NIC.
type StaticConfig struct {
	Interface string
	Hostname  string
	Address   string // "192.168.1.50/24"
	Gateway   string
	DNS       []string
}

// Validate performs basic sanity checks.
func (s StaticConfig) Validate() error {
	if s.Interface == "" {
		return fmt.Errorf("interface is required")
	}
	if s.Hostname == "" {
		return fmt.Errorf("hostname is required")
	}
	if _, _, err := net.ParseCIDR(s.Address); err != nil {
		return fmt.Errorf("address must be CIDR (e.g. 192.168.1.50/24): %w", err)
	}
	if ip := net.ParseIP(s.Gateway); ip == nil {
		return fmt.Errorf("gateway is not a valid IP: %q", s.Gateway)
	}
	for _, d := range s.DNS {
		if ip := net.ParseIP(strings.TrimSpace(d)); ip == nil {
			return fmt.Errorf("dns server is not a valid IP: %q", d)
		}
	}
	return nil
}

// RenderNmstate produces a minimal nmstate YAML for either a DHCP or static
// configuration. The persistent partition picks this up on first boot.
func RenderNmstate(iface string, hostname string, static *StaticConfig) string {
	var b strings.Builder
	b.WriteString("# Generated by novanas-installer\n")
	fmt.Fprintf(&b, "hostname:\n  config: %s\n", hostname)
	b.WriteString("interfaces:\n")
	fmt.Fprintf(&b, "  - name: %s\n", iface)
	b.WriteString("    type: ethernet\n")
	b.WriteString("    state: up\n")
	if static == nil {
		b.WriteString("    ipv4:\n")
		b.WriteString("      enabled: true\n")
		b.WriteString("      dhcp: true\n")
		b.WriteString("    ipv6:\n")
		b.WriteString("      enabled: true\n")
		b.WriteString("      autoconf: true\n")
		b.WriteString("      dhcp: true\n")
		return b.String()
	}
	ip, prefix := splitCIDR(static.Address)
	b.WriteString("    ipv4:\n")
	b.WriteString("      enabled: true\n")
	b.WriteString("      dhcp: false\n")
	b.WriteString("      address:\n")
	fmt.Fprintf(&b, "        - ip: %s\n", ip)
	fmt.Fprintf(&b, "          prefix-length: %d\n", prefix)
	if static.Gateway != "" {
		b.WriteString("routes:\n")
		b.WriteString("  config:\n")
		b.WriteString("    - destination: 0.0.0.0/0\n")
		fmt.Fprintf(&b, "      next-hop-address: %s\n", static.Gateway)
		fmt.Fprintf(&b, "      next-hop-interface: %s\n", iface)
	}
	if len(static.DNS) > 0 {
		b.WriteString("dns-resolver:\n  config:\n    server:\n")
		for _, d := range static.DNS {
			fmt.Fprintf(&b, "      - %s\n", strings.TrimSpace(d))
		}
	}
	return b.String()
}

func splitCIDR(cidr string) (string, int) {
	_, ipnet, err := net.ParseCIDR(cidr)
	if err != nil {
		return cidr, 0
	}
	ones, _ := ipnet.Mask.Size()
	// ParseCIDR returns the network address; prefer the host portion from input.
	parts := strings.SplitN(cidr, "/", 2)
	return parts[0], ones
}
