apiVersion: novanas.io/v1alpha1
kind: AppMetadata
name: radarr
displayName: Radarr
version: 5.11.0
appVersion: 5.11.0
category: arr
description: "A fork of Sonarr to work with movies."
longDescription: |
  Radarr — A fork of Sonarr to work with movies.
  Packaged for NovaNas by the NovaNas team. See upstream project for full
  documentation and support channels.
icon: icon.svg
maintainers:
  - name: NovaNas
    url: https://github.com/azrtydxb/novanas
website: https://radarr.video
source:
  - https://radarr.video
license: GPL-3.0
requirements:
  minRamMB: 512
  minCpu: 1
  requiresGpu: false
  ports: [7878]
tags: [arr]
schema:
  type: object
  properties:
    image:
      type: object
      properties:
        tag:
          type: string
          default: "5.11.0"
          title: "Image tag"
    persistence:
      type: object
      properties:
        config:
          type: object
          properties:
            size:
              type: string
              default: "5Gi"
              title: "Config volume size"
    ingress:
      type: object
      properties:
        enabled:
          type: boolean
          default: true
        host:
          type: string
          default: "radarr.nas.local"
