apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: novanas-storage-agent
  labels:
    app.kubernetes.io/name: novanas
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: novanas-storage-agent
subjects:
  - kind: ServiceAccount
    name: novanas-storage-agent
    namespace: novanas-system
