apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: novanas-storage-csi
  labels:
    app.kubernetes.io/name: novanas
    app.kubernetes.io/component: csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: novanas-storage-csi
subjects:
  - kind: ServiceAccount
    name: novanas-storage-csi
    namespace: novanas-system
