{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: novanas-ui
  namespace: {{ include "novanas.systemNamespace" . }}
  labels:
    {{- include "novanas.componentLabels" (dict "ctx" . "component" "ui") | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "novanas.selectorLabels" (dict "ctx" . "component" "ui") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
{{- end }}
