{{- if .Values.redis.enabled -}}
{{- $ns := include "novanas.systemNamespace" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novanas-redis
  namespace: {{ $ns }}
  labels:
    {{- include "novanas.componentLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "novanas.selectorLabels" (dict "ctx" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "novanas.componentLabels" (dict "ctx" . "component" "redis") | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: redis
          image: "{{ .Values.redis.image.registry }}/{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy | default "IfNotPresent" }}
          args:
            - "--save"
            - "{{ .Values.redis.persistence.save | default "" }}"
            - "--appendonly"
            - "no"
            {{- if .Values.redis.auth.enabled }}
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            {{- end }}
          {{- if .Values.redis.auth.enabled }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: novanas-redis
                  key: redis-password
          {{- end }}
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            {{- toYaml (.Values.redis.resources | default dict) | nindent 12 }}
{{- end }}
