{{- if .Values.redis.enabled -}}
{{- $ns := include "novanas.systemNamespace" . -}}
apiVersion: v1
kind: Service
metadata:
  name: novanas-redis
  namespace: {{ $ns }}
  labels:
    {{- include "novanas.componentLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    {{- include "novanas.selectorLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
{{- end }}
