//go:build !ignore_autogenerated

// Code generation stub.
//
// The real DeepCopy / DeepCopyInto / DeepCopyObject methods for every type
// in this package are produced by controller-gen:
//
//   controller-gen object paths=./api/v1alpha1/...
//
// Until that runs, this file hand-rolls the bare minimum required for the
// types to satisfy runtime.Object so the manager can build. Each generated
// block delegates to a shallow copy (*out = *in); this is sufficient for
// scaffolding purposes and will be replaced wholesale by controller-gen
// output before the operators do real work.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

// ---- StoragePool ----
func (in *StoragePool) DeepCopyInto(out *StoragePool)         { *out = *in }
func (in *StoragePool) DeepCopy() *StoragePool                { if in == nil { return nil }; o := new(StoragePool); in.DeepCopyInto(o); return o }
func (in *StoragePool) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *StoragePoolList) DeepCopyInto(out *StoragePoolList) { *out = *in }
func (in *StoragePoolList) DeepCopy() *StoragePoolList        { if in == nil { return nil }; o := new(StoragePoolList); in.DeepCopyInto(o); return o }
func (in *StoragePoolList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- BlockVolume ----
func (in *BlockVolume) DeepCopyInto(out *BlockVolume)         { *out = *in }
func (in *BlockVolume) DeepCopy() *BlockVolume                { if in == nil { return nil }; o := new(BlockVolume); in.DeepCopyInto(o); return o }
func (in *BlockVolume) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *BlockVolumeList) DeepCopyInto(out *BlockVolumeList) { *out = *in }
func (in *BlockVolumeList) DeepCopy() *BlockVolumeList        { if in == nil { return nil }; o := new(BlockVolumeList); in.DeepCopyInto(o); return o }
func (in *BlockVolumeList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Dataset ----
func (in *Dataset) DeepCopyInto(out *Dataset)         { *out = *in }
func (in *Dataset) DeepCopy() *Dataset                { if in == nil { return nil }; o := new(Dataset); in.DeepCopyInto(o); return o }
func (in *Dataset) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *DatasetList) DeepCopyInto(out *DatasetList) { *out = *in }
func (in *DatasetList) DeepCopy() *DatasetList        { if in == nil { return nil }; o := new(DatasetList); in.DeepCopyInto(o); return o }
func (in *DatasetList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Bucket ----
func (in *Bucket) DeepCopyInto(out *Bucket)         { *out = *in }
func (in *Bucket) DeepCopy() *Bucket                { if in == nil { return nil }; o := new(Bucket); in.DeepCopyInto(o); return o }
func (in *Bucket) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *BucketList) DeepCopyInto(out *BucketList) { *out = *in }
func (in *BucketList) DeepCopy() *BucketList        { if in == nil { return nil }; o := new(BucketList); in.DeepCopyInto(o); return o }
func (in *BucketList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Disk ----
func (in *Disk) DeepCopyInto(out *Disk)         { *out = *in }
func (in *Disk) DeepCopy() *Disk                { if in == nil { return nil }; o := new(Disk); in.DeepCopyInto(o); return o }
func (in *Disk) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *DiskList) DeepCopyInto(out *DiskList) { *out = *in }
func (in *DiskList) DeepCopy() *DiskList        { if in == nil { return nil }; o := new(DiskList); in.DeepCopyInto(o); return o }
func (in *DiskList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Share ----
func (in *Share) DeepCopyInto(out *Share)         { *out = *in }
func (in *Share) DeepCopy() *Share                { if in == nil { return nil }; o := new(Share); in.DeepCopyInto(o); return o }
func (in *Share) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ShareList) DeepCopyInto(out *ShareList) { *out = *in }
func (in *ShareList) DeepCopy() *ShareList        { if in == nil { return nil }; o := new(ShareList); in.DeepCopyInto(o); return o }
func (in *ShareList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- SmbServer ----
func (in *SmbServer) DeepCopyInto(out *SmbServer)         { *out = *in }
func (in *SmbServer) DeepCopy() *SmbServer                { if in == nil { return nil }; o := new(SmbServer); in.DeepCopyInto(o); return o }
func (in *SmbServer) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *SmbServerList) DeepCopyInto(out *SmbServerList) { *out = *in }
func (in *SmbServerList) DeepCopy() *SmbServerList        { if in == nil { return nil }; o := new(SmbServerList); in.DeepCopyInto(o); return o }
func (in *SmbServerList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- NfsServer ----
func (in *NfsServer) DeepCopyInto(out *NfsServer)         { *out = *in }
func (in *NfsServer) DeepCopy() *NfsServer                { if in == nil { return nil }; o := new(NfsServer); in.DeepCopyInto(o); return o }
func (in *NfsServer) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *NfsServerList) DeepCopyInto(out *NfsServerList) { *out = *in }
func (in *NfsServerList) DeepCopy() *NfsServerList        { if in == nil { return nil }; o := new(NfsServerList); in.DeepCopyInto(o); return o }
func (in *NfsServerList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- IscsiTarget ----
func (in *IscsiTarget) DeepCopyInto(out *IscsiTarget)         { *out = *in }
func (in *IscsiTarget) DeepCopy() *IscsiTarget                { if in == nil { return nil }; o := new(IscsiTarget); in.DeepCopyInto(o); return o }
func (in *IscsiTarget) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *IscsiTargetList) DeepCopyInto(out *IscsiTargetList) { *out = *in }
func (in *IscsiTargetList) DeepCopy() *IscsiTargetList        { if in == nil { return nil }; o := new(IscsiTargetList); in.DeepCopyInto(o); return o }
func (in *IscsiTargetList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- NvmeofTarget ----
func (in *NvmeofTarget) DeepCopyInto(out *NvmeofTarget)         { *out = *in }
func (in *NvmeofTarget) DeepCopy() *NvmeofTarget                { if in == nil { return nil }; o := new(NvmeofTarget); in.DeepCopyInto(o); return o }
func (in *NvmeofTarget) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *NvmeofTargetList) DeepCopyInto(out *NvmeofTargetList) { *out = *in }
func (in *NvmeofTargetList) DeepCopy() *NvmeofTargetList        { if in == nil { return nil }; o := new(NvmeofTargetList); in.DeepCopyInto(o); return o }
func (in *NvmeofTargetList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- ObjectStore ----
func (in *ObjectStore) DeepCopyInto(out *ObjectStore)         { *out = *in }
func (in *ObjectStore) DeepCopy() *ObjectStore                { if in == nil { return nil }; o := new(ObjectStore); in.DeepCopyInto(o); return o }
func (in *ObjectStore) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ObjectStoreList) DeepCopyInto(out *ObjectStoreList) { *out = *in }
func (in *ObjectStoreList) DeepCopy() *ObjectStoreList        { if in == nil { return nil }; o := new(ObjectStoreList); in.DeepCopyInto(o); return o }
func (in *ObjectStoreList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- BucketUser ----
func (in *BucketUser) DeepCopyInto(out *BucketUser)         { *out = *in }
func (in *BucketUser) DeepCopy() *BucketUser                { if in == nil { return nil }; o := new(BucketUser); in.DeepCopyInto(o); return o }
func (in *BucketUser) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *BucketUserList) DeepCopyInto(out *BucketUserList) { *out = *in }
func (in *BucketUserList) DeepCopy() *BucketUserList        { if in == nil { return nil }; o := new(BucketUserList); in.DeepCopyInto(o); return o }
func (in *BucketUserList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- User ----
func (in *User) DeepCopyInto(out *User)         { *out = *in }
func (in *User) DeepCopy() *User                { if in == nil { return nil }; o := new(User); in.DeepCopyInto(o); return o }
func (in *User) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *UserList) DeepCopyInto(out *UserList) { *out = *in }
func (in *UserList) DeepCopy() *UserList        { if in == nil { return nil }; o := new(UserList); in.DeepCopyInto(o); return o }
func (in *UserList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Group ----
func (in *Group) DeepCopyInto(out *Group)         { *out = *in }
func (in *Group) DeepCopy() *Group                { if in == nil { return nil }; o := new(Group); in.DeepCopyInto(o); return o }
func (in *Group) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *GroupList) DeepCopyInto(out *GroupList) { *out = *in }
func (in *GroupList) DeepCopy() *GroupList        { if in == nil { return nil }; o := new(GroupList); in.DeepCopyInto(o); return o }
func (in *GroupList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- KeycloakRealm ----
func (in *KeycloakRealm) DeepCopyInto(out *KeycloakRealm)         { *out = *in }
func (in *KeycloakRealm) DeepCopy() *KeycloakRealm                { if in == nil { return nil }; o := new(KeycloakRealm); in.DeepCopyInto(o); return o }
func (in *KeycloakRealm) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *KeycloakRealmList) DeepCopyInto(out *KeycloakRealmList) { *out = *in }
func (in *KeycloakRealmList) DeepCopy() *KeycloakRealmList        { if in == nil { return nil }; o := new(KeycloakRealmList); in.DeepCopyInto(o); return o }
func (in *KeycloakRealmList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- ApiToken ----
func (in *ApiToken) DeepCopyInto(out *ApiToken)         { *out = *in }
func (in *ApiToken) DeepCopy() *ApiToken                { if in == nil { return nil }; o := new(ApiToken); in.DeepCopyInto(o); return o }
func (in *ApiToken) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ApiTokenList) DeepCopyInto(out *ApiTokenList) { *out = *in }
func (in *ApiTokenList) DeepCopy() *ApiTokenList        { if in == nil { return nil }; o := new(ApiTokenList); in.DeepCopyInto(o); return o }
func (in *ApiTokenList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- SshKey ----
func (in *SshKey) DeepCopyInto(out *SshKey)         { *out = *in }
func (in *SshKey) DeepCopy() *SshKey                { if in == nil { return nil }; o := new(SshKey); in.DeepCopyInto(o); return o }
func (in *SshKey) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *SshKeyList) DeepCopyInto(out *SshKeyList) { *out = *in }
func (in *SshKeyList) DeepCopy() *SshKeyList        { if in == nil { return nil }; o := new(SshKeyList); in.DeepCopyInto(o); return o }
func (in *SshKeyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Snapshot ----
func (in *Snapshot) DeepCopyInto(out *Snapshot)         { *out = *in }
func (in *Snapshot) DeepCopy() *Snapshot                { if in == nil { return nil }; o := new(Snapshot); in.DeepCopyInto(o); return o }
func (in *Snapshot) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *SnapshotList) DeepCopyInto(out *SnapshotList) { *out = *in }
func (in *SnapshotList) DeepCopy() *SnapshotList        { if in == nil { return nil }; o := new(SnapshotList); in.DeepCopyInto(o); return o }
func (in *SnapshotList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- SnapshotSchedule ----
func (in *SnapshotSchedule) DeepCopyInto(out *SnapshotSchedule)         { *out = *in }
func (in *SnapshotSchedule) DeepCopy() *SnapshotSchedule                { if in == nil { return nil }; o := new(SnapshotSchedule); in.DeepCopyInto(o); return o }
func (in *SnapshotSchedule) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *SnapshotScheduleList) DeepCopyInto(out *SnapshotScheduleList) { *out = *in }
func (in *SnapshotScheduleList) DeepCopy() *SnapshotScheduleList        { if in == nil { return nil }; o := new(SnapshotScheduleList); in.DeepCopyInto(o); return o }
func (in *SnapshotScheduleList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- ReplicationTarget ----
func (in *ReplicationTarget) DeepCopyInto(out *ReplicationTarget)         { *out = *in }
func (in *ReplicationTarget) DeepCopy() *ReplicationTarget                { if in == nil { return nil }; o := new(ReplicationTarget); in.DeepCopyInto(o); return o }
func (in *ReplicationTarget) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ReplicationTargetList) DeepCopyInto(out *ReplicationTargetList) { *out = *in }
func (in *ReplicationTargetList) DeepCopy() *ReplicationTargetList        { if in == nil { return nil }; o := new(ReplicationTargetList); in.DeepCopyInto(o); return o }
func (in *ReplicationTargetList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- ReplicationJob ----
func (in *ReplicationJob) DeepCopyInto(out *ReplicationJob)         { *out = *in }
func (in *ReplicationJob) DeepCopy() *ReplicationJob                { if in == nil { return nil }; o := new(ReplicationJob); in.DeepCopyInto(o); return o }
func (in *ReplicationJob) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ReplicationJobList) DeepCopyInto(out *ReplicationJobList) { *out = *in }
func (in *ReplicationJobList) DeepCopy() *ReplicationJobList        { if in == nil { return nil }; o := new(ReplicationJobList); in.DeepCopyInto(o); return o }
func (in *ReplicationJobList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- CloudBackupTarget ----
func (in *CloudBackupTarget) DeepCopyInto(out *CloudBackupTarget)         { *out = *in }
func (in *CloudBackupTarget) DeepCopy() *CloudBackupTarget                { if in == nil { return nil }; o := new(CloudBackupTarget); in.DeepCopyInto(o); return o }
func (in *CloudBackupTarget) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *CloudBackupTargetList) DeepCopyInto(out *CloudBackupTargetList) { *out = *in }
func (in *CloudBackupTargetList) DeepCopy() *CloudBackupTargetList        { if in == nil { return nil }; o := new(CloudBackupTargetList); in.DeepCopyInto(o); return o }
func (in *CloudBackupTargetList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- CloudBackupJob ----
func (in *CloudBackupJob) DeepCopyInto(out *CloudBackupJob)         { *out = *in }
func (in *CloudBackupJob) DeepCopy() *CloudBackupJob                { if in == nil { return nil }; o := new(CloudBackupJob); in.DeepCopyInto(o); return o }
func (in *CloudBackupJob) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *CloudBackupJobList) DeepCopyInto(out *CloudBackupJobList) { *out = *in }
func (in *CloudBackupJobList) DeepCopy() *CloudBackupJobList        { if in == nil { return nil }; o := new(CloudBackupJobList); in.DeepCopyInto(o); return o }
func (in *CloudBackupJobList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- ScrubSchedule ----
func (in *ScrubSchedule) DeepCopyInto(out *ScrubSchedule)         { *out = *in }
func (in *ScrubSchedule) DeepCopy() *ScrubSchedule                { if in == nil { return nil }; o := new(ScrubSchedule); in.DeepCopyInto(o); return o }
func (in *ScrubSchedule) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ScrubScheduleList) DeepCopyInto(out *ScrubScheduleList) { *out = *in }
func (in *ScrubScheduleList) DeepCopy() *ScrubScheduleList        { if in == nil { return nil }; o := new(ScrubScheduleList); in.DeepCopyInto(o); return o }
func (in *ScrubScheduleList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- PhysicalInterface ----
func (in *PhysicalInterface) DeepCopyInto(out *PhysicalInterface)         { *out = *in }
func (in *PhysicalInterface) DeepCopy() *PhysicalInterface                { if in == nil { return nil }; o := new(PhysicalInterface); in.DeepCopyInto(o); return o }
func (in *PhysicalInterface) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *PhysicalInterfaceList) DeepCopyInto(out *PhysicalInterfaceList) { *out = *in }
func (in *PhysicalInterfaceList) DeepCopy() *PhysicalInterfaceList        { if in == nil { return nil }; o := new(PhysicalInterfaceList); in.DeepCopyInto(o); return o }
func (in *PhysicalInterfaceList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Bond ----
func (in *Bond) DeepCopyInto(out *Bond)         { *out = *in }
func (in *Bond) DeepCopy() *Bond                { if in == nil { return nil }; o := new(Bond); in.DeepCopyInto(o); return o }
func (in *Bond) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *BondList) DeepCopyInto(out *BondList) { *out = *in }
func (in *BondList) DeepCopy() *BondList        { if in == nil { return nil }; o := new(BondList); in.DeepCopyInto(o); return o }
func (in *BondList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Vlan ----
func (in *Vlan) DeepCopyInto(out *Vlan)         { *out = *in }
func (in *Vlan) DeepCopy() *Vlan                { if in == nil { return nil }; o := new(Vlan); in.DeepCopyInto(o); return o }
func (in *Vlan) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *VlanList) DeepCopyInto(out *VlanList) { *out = *in }
func (in *VlanList) DeepCopy() *VlanList        { if in == nil { return nil }; o := new(VlanList); in.DeepCopyInto(o); return o }
func (in *VlanList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- HostInterface ----
func (in *HostInterface) DeepCopyInto(out *HostInterface)         { *out = *in }
func (in *HostInterface) DeepCopy() *HostInterface                { if in == nil { return nil }; o := new(HostInterface); in.DeepCopyInto(o); return o }
func (in *HostInterface) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *HostInterfaceList) DeepCopyInto(out *HostInterfaceList) { *out = *in }
func (in *HostInterfaceList) DeepCopy() *HostInterfaceList        { if in == nil { return nil }; o := new(HostInterfaceList); in.DeepCopyInto(o); return o }
func (in *HostInterfaceList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- ClusterNetwork ----
func (in *ClusterNetwork) DeepCopyInto(out *ClusterNetwork)         { *out = *in }
func (in *ClusterNetwork) DeepCopy() *ClusterNetwork                { if in == nil { return nil }; o := new(ClusterNetwork); in.DeepCopyInto(o); return o }
func (in *ClusterNetwork) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ClusterNetworkList) DeepCopyInto(out *ClusterNetworkList) { *out = *in }
func (in *ClusterNetworkList) DeepCopy() *ClusterNetworkList        { if in == nil { return nil }; o := new(ClusterNetworkList); in.DeepCopyInto(o); return o }
func (in *ClusterNetworkList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- VipPool ----
func (in *VipPool) DeepCopyInto(out *VipPool)         { *out = *in }
func (in *VipPool) DeepCopy() *VipPool                { if in == nil { return nil }; o := new(VipPool); in.DeepCopyInto(o); return o }
func (in *VipPool) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *VipPoolList) DeepCopyInto(out *VipPoolList) { *out = *in }
func (in *VipPoolList) DeepCopy() *VipPoolList        { if in == nil { return nil }; o := new(VipPoolList); in.DeepCopyInto(o); return o }
func (in *VipPoolList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Ingress ----
func (in *Ingress) DeepCopyInto(out *Ingress)         { *out = *in }
func (in *Ingress) DeepCopy() *Ingress                { if in == nil { return nil }; o := new(Ingress); in.DeepCopyInto(o); return o }
func (in *Ingress) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *IngressList) DeepCopyInto(out *IngressList) { *out = *in }
func (in *IngressList) DeepCopy() *IngressList        { if in == nil { return nil }; o := new(IngressList); in.DeepCopyInto(o); return o }
func (in *IngressList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- RemoteAccessTunnel ----
func (in *RemoteAccessTunnel) DeepCopyInto(out *RemoteAccessTunnel)         { *out = *in }
func (in *RemoteAccessTunnel) DeepCopy() *RemoteAccessTunnel                { if in == nil { return nil }; o := new(RemoteAccessTunnel); in.DeepCopyInto(o); return o }
func (in *RemoteAccessTunnel) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *RemoteAccessTunnelList) DeepCopyInto(out *RemoteAccessTunnelList) { *out = *in }
func (in *RemoteAccessTunnelList) DeepCopy() *RemoteAccessTunnelList        { if in == nil { return nil }; o := new(RemoteAccessTunnelList); in.DeepCopyInto(o); return o }
func (in *RemoteAccessTunnelList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- CustomDomain ----
func (in *CustomDomain) DeepCopyInto(out *CustomDomain)         { *out = *in }
func (in *CustomDomain) DeepCopy() *CustomDomain                { if in == nil { return nil }; o := new(CustomDomain); in.DeepCopyInto(o); return o }
func (in *CustomDomain) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *CustomDomainList) DeepCopyInto(out *CustomDomainList) { *out = *in }
func (in *CustomDomainList) DeepCopy() *CustomDomainList        { if in == nil { return nil }; o := new(CustomDomainList); in.DeepCopyInto(o); return o }
func (in *CustomDomainList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- FirewallRule ----
func (in *FirewallRule) DeepCopyInto(out *FirewallRule)         { *out = *in }
func (in *FirewallRule) DeepCopy() *FirewallRule                { if in == nil { return nil }; o := new(FirewallRule); in.DeepCopyInto(o); return o }
func (in *FirewallRule) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *FirewallRuleList) DeepCopyInto(out *FirewallRuleList) { *out = *in }
func (in *FirewallRuleList) DeepCopy() *FirewallRuleList        { if in == nil { return nil }; o := new(FirewallRuleList); in.DeepCopyInto(o); return o }
func (in *FirewallRuleList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- TrafficPolicy ----
func (in *TrafficPolicy) DeepCopyInto(out *TrafficPolicy)         { *out = *in }
func (in *TrafficPolicy) DeepCopy() *TrafficPolicy                { if in == nil { return nil }; o := new(TrafficPolicy); in.DeepCopyInto(o); return o }
func (in *TrafficPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *TrafficPolicyList) DeepCopyInto(out *TrafficPolicyList) { *out = *in }
func (in *TrafficPolicyList) DeepCopy() *TrafficPolicyList        { if in == nil { return nil }; o := new(TrafficPolicyList); in.DeepCopyInto(o); return o }
func (in *TrafficPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- AppCatalog ----
func (in *AppCatalog) DeepCopyInto(out *AppCatalog)         { *out = *in }
func (in *AppCatalog) DeepCopy() *AppCatalog                { if in == nil { return nil }; o := new(AppCatalog); in.DeepCopyInto(o); return o }
func (in *AppCatalog) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *AppCatalogList) DeepCopyInto(out *AppCatalogList) { *out = *in }
func (in *AppCatalogList) DeepCopy() *AppCatalogList        { if in == nil { return nil }; o := new(AppCatalogList); in.DeepCopyInto(o); return o }
func (in *AppCatalogList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- App ----
func (in *App) DeepCopyInto(out *App)         { *out = *in }
func (in *App) DeepCopy() *App                { if in == nil { return nil }; o := new(App); in.DeepCopyInto(o); return o }
func (in *App) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *AppList) DeepCopyInto(out *AppList) { *out = *in }
func (in *AppList) DeepCopy() *AppList        { if in == nil { return nil }; o := new(AppList); in.DeepCopyInto(o); return o }
func (in *AppList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- AppInstance ----
func (in *AppInstance) DeepCopyInto(out *AppInstance)         { *out = *in }
func (in *AppInstance) DeepCopy() *AppInstance                { if in == nil { return nil }; o := new(AppInstance); in.DeepCopyInto(o); return o }
func (in *AppInstance) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *AppInstanceList) DeepCopyInto(out *AppInstanceList) { *out = *in }
func (in *AppInstanceList) DeepCopy() *AppInstanceList        { if in == nil { return nil }; o := new(AppInstanceList); in.DeepCopyInto(o); return o }
func (in *AppInstanceList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Vm ----
func (in *Vm) DeepCopyInto(out *Vm)         { *out = *in }
func (in *Vm) DeepCopy() *Vm                { if in == nil { return nil }; o := new(Vm); in.DeepCopyInto(o); return o }
func (in *Vm) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *VmList) DeepCopyInto(out *VmList) { *out = *in }
func (in *VmList) DeepCopy() *VmList        { if in == nil { return nil }; o := new(VmList); in.DeepCopyInto(o); return o }
func (in *VmList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- IsoLibrary ----
func (in *IsoLibrary) DeepCopyInto(out *IsoLibrary)         { *out = *in }
func (in *IsoLibrary) DeepCopy() *IsoLibrary                { if in == nil { return nil }; o := new(IsoLibrary); in.DeepCopyInto(o); return o }
func (in *IsoLibrary) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *IsoLibraryList) DeepCopyInto(out *IsoLibraryList) { *out = *in }
func (in *IsoLibraryList) DeepCopy() *IsoLibraryList        { if in == nil { return nil }; o := new(IsoLibraryList); in.DeepCopyInto(o); return o }
func (in *IsoLibraryList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- GpuDevice ----
func (in *GpuDevice) DeepCopyInto(out *GpuDevice)         { *out = *in }
func (in *GpuDevice) DeepCopy() *GpuDevice                { if in == nil { return nil }; o := new(GpuDevice); in.DeepCopyInto(o); return o }
func (in *GpuDevice) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *GpuDeviceList) DeepCopyInto(out *GpuDeviceList) { *out = *in }
func (in *GpuDeviceList) DeepCopy() *GpuDeviceList        { if in == nil { return nil }; o := new(GpuDeviceList); in.DeepCopyInto(o); return o }
func (in *GpuDeviceList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- EncryptionPolicy ----
func (in *EncryptionPolicy) DeepCopyInto(out *EncryptionPolicy)         { *out = *in }
func (in *EncryptionPolicy) DeepCopy() *EncryptionPolicy                { if in == nil { return nil }; o := new(EncryptionPolicy); in.DeepCopyInto(o); return o }
func (in *EncryptionPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *EncryptionPolicyList) DeepCopyInto(out *EncryptionPolicyList) { *out = *in }
func (in *EncryptionPolicyList) DeepCopy() *EncryptionPolicyList        { if in == nil { return nil }; o := new(EncryptionPolicyList); in.DeepCopyInto(o); return o }
func (in *EncryptionPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- KmsKey ----
func (in *KmsKey) DeepCopyInto(out *KmsKey)         { *out = *in }
func (in *KmsKey) DeepCopy() *KmsKey                { if in == nil { return nil }; o := new(KmsKey); in.DeepCopyInto(o); return o }
func (in *KmsKey) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *KmsKeyList) DeepCopyInto(out *KmsKeyList) { *out = *in }
func (in *KmsKeyList) DeepCopy() *KmsKeyList        { if in == nil { return nil }; o := new(KmsKeyList); in.DeepCopyInto(o); return o }
func (in *KmsKeyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- Certificate ----
func (in *Certificate) DeepCopyInto(out *Certificate)         { *out = *in }
func (in *Certificate) DeepCopy() *Certificate                { if in == nil { return nil }; o := new(Certificate); in.DeepCopyInto(o); return o }
func (in *Certificate) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *CertificateList) DeepCopyInto(out *CertificateList) { *out = *in }
func (in *CertificateList) DeepCopy() *CertificateList        { if in == nil { return nil }; o := new(CertificateList); in.DeepCopyInto(o); return o }
func (in *CertificateList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- SmartPolicy ----
func (in *SmartPolicy) DeepCopyInto(out *SmartPolicy)         { *out = *in }
func (in *SmartPolicy) DeepCopy() *SmartPolicy                { if in == nil { return nil }; o := new(SmartPolicy); in.DeepCopyInto(o); return o }
func (in *SmartPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *SmartPolicyList) DeepCopyInto(out *SmartPolicyList) { *out = *in }
func (in *SmartPolicyList) DeepCopy() *SmartPolicyList        { if in == nil { return nil }; o := new(SmartPolicyList); in.DeepCopyInto(o); return o }
func (in *SmartPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- AlertChannel ----
func (in *AlertChannel) DeepCopyInto(out *AlertChannel)         { *out = *in }
func (in *AlertChannel) DeepCopy() *AlertChannel                { if in == nil { return nil }; o := new(AlertChannel); in.DeepCopyInto(o); return o }
func (in *AlertChannel) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *AlertChannelList) DeepCopyInto(out *AlertChannelList) { *out = *in }
func (in *AlertChannelList) DeepCopy() *AlertChannelList        { if in == nil { return nil }; o := new(AlertChannelList); in.DeepCopyInto(o); return o }
func (in *AlertChannelList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- AlertPolicy ----
func (in *AlertPolicy) DeepCopyInto(out *AlertPolicy)         { *out = *in }
func (in *AlertPolicy) DeepCopy() *AlertPolicy                { if in == nil { return nil }; o := new(AlertPolicy); in.DeepCopyInto(o); return o }
func (in *AlertPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *AlertPolicyList) DeepCopyInto(out *AlertPolicyList) { *out = *in }
func (in *AlertPolicyList) DeepCopy() *AlertPolicyList        { if in == nil { return nil }; o := new(AlertPolicyList); in.DeepCopyInto(o); return o }
func (in *AlertPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- AuditPolicy ----
func (in *AuditPolicy) DeepCopyInto(out *AuditPolicy)         { *out = *in }
func (in *AuditPolicy) DeepCopy() *AuditPolicy                { if in == nil { return nil }; o := new(AuditPolicy); in.DeepCopyInto(o); return o }
func (in *AuditPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *AuditPolicyList) DeepCopyInto(out *AuditPolicyList) { *out = *in }
func (in *AuditPolicyList) DeepCopy() *AuditPolicyList        { if in == nil { return nil }; o := new(AuditPolicyList); in.DeepCopyInto(o); return o }
func (in *AuditPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- ServiceLevelObjective ----
func (in *ServiceLevelObjective) DeepCopyInto(out *ServiceLevelObjective)         { *out = *in }
func (in *ServiceLevelObjective) DeepCopy() *ServiceLevelObjective                { if in == nil { return nil }; o := new(ServiceLevelObjective); in.DeepCopyInto(o); return o }
func (in *ServiceLevelObjective) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ServiceLevelObjectiveList) DeepCopyInto(out *ServiceLevelObjectiveList) { *out = *in }
func (in *ServiceLevelObjectiveList) DeepCopy() *ServiceLevelObjectiveList        { if in == nil { return nil }; o := new(ServiceLevelObjectiveList); in.DeepCopyInto(o); return o }
func (in *ServiceLevelObjectiveList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- UpsPolicy ----
func (in *UpsPolicy) DeepCopyInto(out *UpsPolicy)         { *out = *in }
func (in *UpsPolicy) DeepCopy() *UpsPolicy                { if in == nil { return nil }; o := new(UpsPolicy); in.DeepCopyInto(o); return o }
func (in *UpsPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *UpsPolicyList) DeepCopyInto(out *UpsPolicyList) { *out = *in }
func (in *UpsPolicyList) DeepCopy() *UpsPolicyList        { if in == nil { return nil }; o := new(UpsPolicyList); in.DeepCopyInto(o); return o }
func (in *UpsPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- ConfigBackupPolicy ----
func (in *ConfigBackupPolicy) DeepCopyInto(out *ConfigBackupPolicy)         { *out = *in }
func (in *ConfigBackupPolicy) DeepCopy() *ConfigBackupPolicy                { if in == nil { return nil }; o := new(ConfigBackupPolicy); in.DeepCopyInto(o); return o }
func (in *ConfigBackupPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ConfigBackupPolicyList) DeepCopyInto(out *ConfigBackupPolicyList) { *out = *in }
func (in *ConfigBackupPolicyList) DeepCopy() *ConfigBackupPolicyList        { if in == nil { return nil }; o := new(ConfigBackupPolicyList); in.DeepCopyInto(o); return o }
func (in *ConfigBackupPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- SystemSettings ----
func (in *SystemSettings) DeepCopyInto(out *SystemSettings)         { *out = *in }
func (in *SystemSettings) DeepCopy() *SystemSettings                { if in == nil { return nil }; o := new(SystemSettings); in.DeepCopyInto(o); return o }
func (in *SystemSettings) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *SystemSettingsList) DeepCopyInto(out *SystemSettingsList) { *out = *in }
func (in *SystemSettingsList) DeepCopy() *SystemSettingsList        { if in == nil { return nil }; o := new(SystemSettingsList); in.DeepCopyInto(o); return o }
func (in *SystemSettingsList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- UpdatePolicy ----
func (in *UpdatePolicy) DeepCopyInto(out *UpdatePolicy)         { *out = *in }
func (in *UpdatePolicy) DeepCopy() *UpdatePolicy                { if in == nil { return nil }; o := new(UpdatePolicy); in.DeepCopyInto(o); return o }
func (in *UpdatePolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *UpdatePolicyList) DeepCopyInto(out *UpdatePolicyList) { *out = *in }
func (in *UpdatePolicyList) DeepCopy() *UpdatePolicyList        { if in == nil { return nil }; o := new(UpdatePolicyList); in.DeepCopyInto(o); return o }
func (in *UpdatePolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// ---- ServicePolicy ----
func (in *ServicePolicy) DeepCopyInto(out *ServicePolicy)         { *out = *in }
func (in *ServicePolicy) DeepCopy() *ServicePolicy                { if in == nil { return nil }; o := new(ServicePolicy); in.DeepCopyInto(o); return o }
func (in *ServicePolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ServicePolicyList) DeepCopyInto(out *ServicePolicyList) { *out = *in }
func (in *ServicePolicyList) DeepCopy() *ServicePolicyList        { if in == nil { return nil }; o := new(ServicePolicyList); in.DeepCopyInto(o); return o }
func (in *ServicePolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

