//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockVolume) DeepCopyInto(out *BlockVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockVolume.
func (in *BlockVolume) DeepCopy() *BlockVolume {
	if in == nil {
		return nil
	}
	out := new(BlockVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlockVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockVolumeList) DeepCopyInto(out *BlockVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlockVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockVolumeList.
func (in *BlockVolumeList) DeepCopy() *BlockVolumeList {
	if in == nil {
		return nil
	}
	out := new(BlockVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlockVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockVolumeSpec) DeepCopyInto(out *BlockVolumeSpec) {
	*out = *in
	if in.Protection != nil {
		in, out := &in.Protection, &out.Protection
		*out = new(ProtectionPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(EncryptionSettings)
		**out = **in
	}
	if in.Tiering != nil {
		in, out := &in.Tiering, &out.Tiering
		*out = new(TieringPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockVolumeSpec.
func (in *BlockVolumeSpec) DeepCopy() *BlockVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(BlockVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockVolumeStatus) DeepCopyInto(out *BlockVolumeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(EncryptionStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockVolumeStatus.
func (in *BlockVolumeStatus) DeepCopy() *BlockVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(BlockVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionSettings) DeepCopyInto(out *EncryptionSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionSettings.
func (in *EncryptionSettings) DeepCopy() *EncryptionSettings {
	if in == nil {
		return nil
	}
	out := new(EncryptionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionStatus) DeepCopyInto(out *EncryptionStatus) {
	*out = *in
	if in.WrappedDK != nil {
		in, out := &in.WrappedDK, &out.WrappedDK
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.ProvisionedAt != nil {
		in, out := &in.ProvisionedAt, &out.ProvisionedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionStatus.
func (in *EncryptionStatus) DeepCopy() *EncryptionStatus {
	if in == nil {
		return nil
	}
	out := new(EncryptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErasureCodingSpec) DeepCopyInto(out *ErasureCodingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErasureCodingSpec.
func (in *ErasureCodingSpec) DeepCopy() *ErasureCodingSpec {
	if in == nil {
		return nil
	}
	out := new(ErasureCodingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectionPolicy) DeepCopyInto(out *ProtectionPolicy) {
	*out = *in
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(ReplicationProtection)
		**out = **in
	}
	if in.ErasureCoding != nil {
		in, out := &in.ErasureCoding, &out.ErasureCoding
		*out = new(ErasureCodingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectionPolicy.
func (in *ProtectionPolicy) DeepCopy() *ProtectionPolicy {
	if in == nil {
		return nil
	}
	out := new(ProtectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationProtection) DeepCopyInto(out *ReplicationProtection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationProtection.
func (in *ReplicationProtection) DeepCopy() *ReplicationProtection {
	if in == nil {
		return nil
	}
	out := new(ReplicationProtection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TieringPolicy) DeepCopyInto(out *TieringPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TieringPolicy.
func (in *TieringPolicy) DeepCopy() *TieringPolicy {
	if in == nil {
		return nil
	}
	out := new(TieringPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vm) DeepCopyInto(out *Vm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vm.
func (in *Vm) DeepCopy() *Vm {
	if in == nil {
		return nil
	}
	out := new(Vm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmCdrom) DeepCopyInto(out *VmCdrom) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmCdrom.
func (in *VmCdrom) DeepCopy() *VmCdrom {
	if in == nil {
		return nil
	}
	out := new(VmCdrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmCdromSource) DeepCopyInto(out *VmCdromSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmCdromSource.
func (in *VmCdromSource) DeepCopy() *VmCdromSource {
	if in == nil {
		return nil
	}
	out := new(VmCdromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmDisk) DeepCopyInto(out *VmDisk) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmDisk.
func (in *VmDisk) DeepCopy() *VmDisk {
	if in == nil {
		return nil
	}
	out := new(VmDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmDiskSource) DeepCopyInto(out *VmDiskSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmDiskSource.
func (in *VmDiskSource) DeepCopy() *VmDiskSource {
	if in == nil {
		return nil
	}
	out := new(VmDiskSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmGpu) DeepCopyInto(out *VmGpu) {
	*out = *in
	if in.Passthrough != nil {
		in, out := &in.Passthrough, &out.Passthrough
		*out = make([]VmGpuPassthroughEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmGpu.
func (in *VmGpu) DeepCopy() *VmGpu {
	if in == nil {
		return nil
	}
	out := new(VmGpu)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmGpuPassthroughEntry) DeepCopyInto(out *VmGpuPassthroughEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmGpuPassthroughEntry.
func (in *VmGpuPassthroughEntry) DeepCopy() *VmGpuPassthroughEntry {
	if in == nil {
		return nil
	}
	out := new(VmGpuPassthroughEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmGraphics) DeepCopyInto(out *VmGraphics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmGraphics.
func (in *VmGraphics) DeepCopy() *VmGraphics {
	if in == nil {
		return nil
	}
	out := new(VmGraphics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmList) DeepCopyInto(out *VmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmList.
func (in *VmList) DeepCopy() *VmList {
	if in == nil {
		return nil
	}
	out := new(VmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmNetwork) DeepCopyInto(out *VmNetwork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmNetwork.
func (in *VmNetwork) DeepCopy() *VmNetwork {
	if in == nil {
		return nil
	}
	out := new(VmNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmOS) DeepCopyInto(out *VmOS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmOS.
func (in *VmOS) DeepCopy() *VmOS {
	if in == nil {
		return nil
	}
	out := new(VmOS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmResources) DeepCopyInto(out *VmResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmResources.
func (in *VmResources) DeepCopy() *VmResources {
	if in == nil {
		return nil
	}
	out := new(VmResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmSpec) DeepCopyInto(out *VmSpec) {
	*out = *in
	out.OS = in.OS
	out.Resources = in.Resources
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]VmDisk, len(*in))
		copy(*out, *in)
	}
	if in.Cdrom != nil {
		in, out := &in.Cdrom, &out.Cdrom
		*out = make([]VmCdrom, len(*in))
		copy(*out, *in)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = make([]VmNetwork, len(*in))
		copy(*out, *in)
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(VmGpu)
		(*in).DeepCopyInto(*out)
	}
	if in.Graphics != nil {
		in, out := &in.Graphics, &out.Graphics
		*out = new(VmGraphics)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmSpec.
func (in *VmSpec) DeepCopy() *VmSpec {
	if in == nil {
		return nil
	}
	out := new(VmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmStatus) DeepCopyInto(out *VmStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmStatus.
func (in *VmStatus) DeepCopy() *VmStatus {
	if in == nil {
		return nil
	}
	out := new(VmStatus)
	in.DeepCopyInto(out)
	return out
}
