---
apiVersion: novanas.io/v1alpha1
kind: Share
metadata:
  name: photos
spec:
  dataset: photos
  path: /photos
  protocols:
    smb:
      caseSensitive: false
    nfs:
      allowedNetworks:
        - 10.0.0.0/8
        - 192.168.0.0/16
