package install

import (
	"fmt"
	"os"
	"path/filepath"
)

// GrubInstaller installs GRUB onto the EFI partition and writes grub.cfg.
type GrubInstaller struct {
	DryRun bool
	Log    func(format string, args ...any)
	Exec   func(name string, args ...string) error
}

// Install runs grub-install for x86_64-efi and writes a minimal config that
// boots slot A by default, with slot B as the RAUC standby target.
func (g *GrubInstaller) Install(efiDir, bootDir string) error {
	if g.Log != nil {
		g.Log("grub-install efi=%s boot=%s", efiDir, bootDir)
	}
	if !g.DryRun && g.Exec != nil {
		if err := g.Exec("grub-install",
			"--target=x86_64-efi",
			fmt.Sprintf("--efi-directory=%s", efiDir),
			fmt.Sprintf("--boot-directory=%s", bootDir),
			"--bootloader-id=novanas",
			"--removable",
		); err != nil {
			return err
		}
	}
	cfg := RenderGrubConfig()
	return writeFile(filepath.Join(bootDir, "grub", "grub.cfg"), cfg, g.DryRun)
}

// RenderGrubConfig returns a minimal A/B grub.cfg compatible with RAUC's
// BOOT_ORDER semantics.
func RenderGrubConfig() string {
	return `# Generated by novanas-installer
set default=A
set timeout=3

# RAUC A/B state lives on the Boot partition via grub-env
load_env --file=/grubenv

if [ -n "${BOOT_ORDER}" ]; then
    set default="${BOOT_ORDER%% *}"
fi

menuentry "NovaNas (Slot A)" --id A {
    search --no-floppy --label os-a --set=root
    linux   /boot/vmlinuz root=LABEL=os-a ro quiet rauc.slot=A
    initrd  /boot/initrd.img
}

menuentry "NovaNas (Slot B)" --id B {
    search --no-floppy --label os-b --set=root
    linux   /boot/vmlinuz root=LABEL=os-b ro quiet rauc.slot=B
    initrd  /boot/initrd.img
}
`
}

func writeFile(path, contents string, dryRun bool) error {
	if dryRun {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(contents), 0o644)
}
